import { API } from './apiPrefix';

function headers(token: string) {
  return {
    'Content-Type': 'application/json',
    Authorization: `Bearer ${token}`,
  };
}

export type OrderFormTemplateStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';

export type OrderFormTemplateRenderMode = 'STANDARD' | 'TEMPLATE';

export type OrderFormFieldInputType =
  | 'TEXT'
  | 'TEXTAREA'
  | 'NUMBER'
  | 'MONEY'
  | 'DATE'
  | 'TIME'
  | 'PHONE'
  | 'ADDRESS'
  | 'SELECT'
  | 'MULTISELECT'
  | 'CHECKBOX'
  | 'PHOTO';

export type OrderFormFieldFillMode = 'CUSTOMER' | 'ADMIN_LOCKED' | 'ADMIN_PREFILL';

export interface OrderFormTemplateField {
  id?: string;
  fieldKey: string;
  label: string;
  helpText: string | null;
  inputType: OrderFormFieldInputType;
  options: unknown;
  required: boolean;
  sortOrder: number;
  systemField: string | null;
  fillMode: OrderFormFieldFillMode;
}

export interface OrderFormTemplate {
  id: string;
  title: string;
  icon: string | null;
  description: string | null;
  status: OrderFormTemplateStatus;
  renderMode: OrderFormTemplateRenderMode;
  version: number;
  isDefault: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
  fields: OrderFormTemplateField[];
}

export interface OrderFormSystemFieldDef {
  key: string;
  label: string;
  inquiryColumn: string;
  requiredCore: boolean;
  templateRequired?: boolean;
  autoGenerated: boolean;
  inputType: string;
  sectionToggle?: boolean;
}

const BASE = `${API}/orderform-templates`;

async function parseError(res: Response, fallback: string): Promise<never> {
  const err = await res.json().catch(() => ({}));
  throw new Error((err as { error?: string }).error || fallback);
}

export async function getSystemFields(token: string): Promise<OrderFormSystemFieldDef[]> {
  const res = await fetch(`${BASE}/system-fields`, { headers: headers(token) });
  if (!res.ok) await parseError(res, '시스템 필드를 불러올 수 없습니다.');
  const data = (await res.json()) as { items: OrderFormSystemFieldDef[] };
  return data.items ?? [];
}

export async function listOrderFormTemplates(token: string): Promise<OrderFormTemplate[]> {
  const res = await fetch(`${BASE}`, { headers: headers(token) });
  if (!res.ok) await parseError(res, '발주서 템플릿을 불러올 수 없습니다.');
  const data = (await res.json()) as { items: OrderFormTemplate[] };
  return data.items ?? [];
}

export async function getOrderFormTemplate(token: string, id: string): Promise<OrderFormTemplate> {
  const res = await fetch(`${BASE}/${encodeURIComponent(id)}`, { headers: headers(token) });
  if (!res.ok) await parseError(res, '템플릿을 불러올 수 없습니다.');
  const data = (await res.json()) as { template: OrderFormTemplate };
  return data.template;
}

export async function createOrderFormTemplate(
  token: string,
  data: { title: string; icon?: string | null; description?: string | null; renderMode?: OrderFormTemplateRenderMode },
): Promise<OrderFormTemplate> {
  const res = await fetch(`${BASE}`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify(data),
  });
  if (!res.ok) await parseError(res, '템플릿 생성에 실패했습니다.');
  return ((await res.json()) as { template: OrderFormTemplate }).template;
}

export async function updateOrderFormTemplateMeta(
  token: string,
  id: string,
  data: { title?: string; icon?: string | null; description?: string | null; sortOrder?: number; renderMode?: OrderFormTemplateRenderMode },
): Promise<OrderFormTemplate> {
  const res = await fetch(`${BASE}/${encodeURIComponent(id)}`, {
    method: 'PATCH',
    headers: headers(token),
    body: JSON.stringify(data),
  });
  if (!res.ok) await parseError(res, '템플릿 수정에 실패했습니다.');
  return ((await res.json()) as { template: OrderFormTemplate }).template;
}

export async function saveOrderFormTemplateFields(
  token: string,
  id: string,
  fields: Array<Omit<OrderFormTemplateField, 'id'>>,
): Promise<OrderFormTemplate> {
  const res = await fetch(`${BASE}/${encodeURIComponent(id)}/fields`, {
    method: 'PUT',
    headers: headers(token),
    body: JSON.stringify({ fields }),
  });
  if (!res.ok) await parseError(res, '필드 저장에 실패했습니다.');
  return ((await res.json()) as { template: OrderFormTemplate }).template;
}

export async function publishOrderFormTemplate(token: string, id: string): Promise<OrderFormTemplate> {
  const res = await fetch(`${BASE}/${encodeURIComponent(id)}/publish`, {
    method: 'POST',
    headers: headers(token),
  });
  if (!res.ok) await parseError(res, '발행에 실패했습니다.');
  return ((await res.json()) as { template: OrderFormTemplate }).template;
}

export async function unpublishOrderFormTemplate(token: string, id: string): Promise<OrderFormTemplate> {
  const res = await fetch(`${BASE}/${encodeURIComponent(id)}/unpublish`, {
    method: 'POST',
    headers: headers(token),
  });
  if (!res.ok) await parseError(res, '발행 해제에 실패했습니다.');
  return ((await res.json()) as { template: OrderFormTemplate }).template;
}

export async function duplicateOrderFormTemplate(token: string, id: string): Promise<OrderFormTemplate> {
  const res = await fetch(`${BASE}/${encodeURIComponent(id)}/duplicate`, {
    method: 'POST',
    headers: headers(token),
  });
  if (!res.ok) await parseError(res, '복제에 실패했습니다.');
  return ((await res.json()) as { template: OrderFormTemplate }).template;
}

export async function deleteOrderFormTemplate(token: string, id: string, password: string): Promise<void> {
  const res = await fetch(`${BASE}/${encodeURIComponent(id)}/delete`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify({ password }),
  });
  if (!res.ok) await parseError(res, '삭제에 실패했습니다.');
}
