@echo off
cd /d "%~dp0"
echo [1/3] Stop old bridge on port 17890...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :17890 ^| findstr LISTENING') do taskkill /F /PID %%a
ping 127.0.0.1 -n 2 > NUL
echo [2/3] Check Python packages...
python -m pip install -r requirements.txt -q
echo [3/3] Start Soomgo bridge v2...
python server.py
