export const OUTBOUND_EMAIL_COPY = {
  pageTitle: '발송 이메일 설정',
  pageIntro:
    '견적서·현장 완료본 등 고객에게 보내는 메일을, 우리 업체 메일 주소로 보내도록 연결합니다.',
  scopeTitle: '이 설정은 누구 메일로 보내나요?',
  scopeCommon: '업체 공통',
  scopeBrandHint: (brand: string) =>
    `${brand} 고객 메일은 여기서 연결한 메일로만 보냅니다. 비워 두면 해당 브랜드로는 메일을 보내지 않습니다(다른 업체 메일로 대체하지 않음).`,
  scopeCommonHint: '브랜드가 없는 접수·공통 안내용 기본 메일 연결입니다.',
  fallbackPlatform:
    '아래를 비워 두면 청소비서 기본 메일로 보낼 수 있습니다. 고객에게 우리 업체 이름·메일로 보이게 하려면 여기서 설정하세요.',
  fallbackBrandEffective: (brand: string) =>
    `${brand} 전용 발송 이메일이 없습니다. 이 브랜드 메일은 보낼 수 없으며, 다른 업체 메일로 대신 보내지 않습니다.`,
  statusReady: '메일 보내기 준비됨',
  statusFallback: '다른 설정으로 메일을 보냅니다',
  statusMissing: '아직 메일을 보낼 수 없습니다',
  sectionTitle: '메일 보내기 연결',
  guideButton: '자세한 설명 보기',
  stepProvider: '어떤 메일을 쓰시나요?',
  stepEmail: '보낼 메일 주소',
  stepName: '받는 사람에게 보이는 이름',
  stepPassword: '메일 연동 비밀번호',
  stepTest: '연습 보내기',
  sendEmailHint: '메일함에 로그인할 때 쓰는 주소 전체 (@ 포함)',
  displayNameHint: '고객 메일함에 「발신: ○○」처럼 보이는 이름',
  passwordHint: '로그인 비밀번호와 다릅니다. 메일 연동용 비밀번호만 입력하세요.',
  passwordConfiguredPlaceholder: '●●●●●●●● (바꿀 때만 다시 입력)',
  testEmailHint: '저장 후 같은 설정으로 연습 메일을 보냅니다. 스팸함도 확인해 주세요.',
  testEmailLabel: '연습 보낼 내 메일',
  save: '저장',
  saveAndTest: '저장하고 연습 메일 보내기',
  testOnly: '연습 메일 보내기',
  saving: '저장 중…',
  testing: '보내는 중…',
  advancedToggle: '고급 설정 (메일 회사 서버·연결 번호 직접 바꾸기)',
  advancedHost: '메일 회사 서버 주소',
  advancedPort: '연결 번호',
  advancedSecure: '보안 연결(잠금) 사용',
  advancedSecureHint: 'Gmail 587은 끄기 · 네이버·다음 465는 켜기',
  viewAllFields: '한 번에 보기 (고급)',
  viewWizard: '단계별로 설정하기',
  prev: '이전',
  next: '다음',
  successSave: (scope: string) => `${scope} 메일 연결 설정이 저장되었습니다.`,
  successTest: '연습 메일을 보냈습니다. 받은편지함(스팸함)을 확인해 주세요.',
  successSaveAndTest:
    '설정을 저장하고 연습 메일을 보냈습니다. 받은편지함(스팸함)을 확인해 주세요.',
} as const;
