import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { getToken } from '../../stores/auth';
import { ConfirmPasswordModal } from '../../components/admin/ConfirmPasswordModal';
import { OrderFormTemplatePreview } from '../../components/admin/OrderFormTemplatePreview';
import { HelpTooltip } from '../../components/ui/HelpTooltip';
import { PageTitleWithFavorite } from '../../components/layout/NavFavoritePageTitle';
import { getDesignerPreviewOrderToken } from '../../api/orderform';
import { appendPublicQuery } from '../../utils/publicTenantQuery';
import { withOrderFormPreviewWalkQuery } from '@shared/orderFormPreviewWalk';
import { useStaffTenantSlugForLinks } from '../../hooks/useStaffTenantSlugForLinks';
import {
  deleteOrderFormTemplate,
  duplicateOrderFormTemplate,
  getPromotedOrderFormListFields,
  getSystemFields,
  listOrderFormTemplates,
  publishOrderFormTemplate,
  saveOrderFormTemplateFields,
  unpublishOrderFormTemplate,
  updateOrderFormTemplateMeta,
  type OrderFormFieldFillMode,
  type OrderFormFieldInputType,
  type OrderFormSystemFieldDef,
  type OrderFormTemplate,
  type OrderFormTemplateRenderMode,
} from '../../api/orderFormTemplates';
import { ORDER_FORM_INQUIRY_LIST_PROMOTED_MAX } from '@shared/orderFormListSnapshot';
import {
  ORDER_FORM_PHOTOS_SECTION_KEY,
  isOrderFormSectionToggleKey,
  isOrderFormSectionToggleOn,
  optionsForOrderFormSectionToggle,
} from '@shared/orderFormSectionToggles';
import { OrderFormSectionToggles } from '../../components/admin/order-templates/OrderFormSectionToggles';
import { OrderFormTemplateCreateWizard } from '../../components/admin/order-templates/OrderFormTemplateCreateWizard';
import { OrderFormTemplateListPanel } from '../../components/admin/order-templates/OrderFormTemplateListPanel';
import { OrderFormTemplateStatusBadge } from '../../components/admin/order-templates/orderFormTemplateStatus';
import {
  FILL_MODE_OPTIONS,
  ICON_OPTIONS,
  INPUT_TYPE_OPTIONS,
  OPTION_INPUT_TYPES,
  canPromoteDraftField,
  coreFieldToDraft,
  draftsToPayload,
  fieldToDraft,
  requiredFieldsForMode,
  type DraftField,
} from '../../components/admin/order-templates/orderFormTemplateDraft';

export function AdminOrderFormTemplatesPage() {
  const token = getToken() ?? '';
  const staffTenantSlug = useStaffTenantSlugForLinks(token || null);
  const [searchParams, setSearchParams] = useSearchParams();
  const isCreate = searchParams.get('new') === '1';
  const urlId = searchParams.get('id');
  const wizardStep = (() => {
    const n = parseInt(searchParams.get('step') || '1', 10);
    if (!Number.isFinite(n) || n < 1) return 1;
    return Math.min(3, n);
  })();
  const [templates, setTemplates] = useState<OrderFormTemplate[]>([]);
  const [systemFields, setSystemFields] = useState<OrderFormSystemFieldDef[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [designerPreviewToken, setDesignerPreviewToken] = useState<string | null>(null);
  const [designerPreviewIframeKey, setDesignerPreviewIframeKey] = useState(0);

  // 편집 상태
  const [meta, setMeta] = useState({ title: '', icon: '', description: '' });
  const [drafts, setDrafts] = useState<DraftField[]>([]);
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [iconOpen, setIconOpen] = useState(false);
  const [tenantPromotedKeys, setTenantPromotedKeys] = useState<Set<string>>(new Set());
  const [togglingId, setTogglingId] = useState<string | null>(null);

  const selected = useMemo(() => templates.find((t) => t.id === selectedId) ?? null, [templates, selectedId]);

  // 발주서 형식은 자동: 기본 발주서=표준 폼 전체(STANDARD), 그 외=내가 만든 항목만(TEMPLATE)
  const editMode: OrderFormTemplateRenderMode = selected?.isDefault ? 'STANDARD' : 'TEMPLATE';
  const requiredCoreFields = useMemo(
    () => requiredFieldsForMode(systemFields, editMode),
    [systemFields, editMode],
  );
  const mappedSystemKeys = useMemo(() => new Set(drafts.map((d) => d.systemField).filter(Boolean) as string[]), [drafts]);
  const unusedConnectableFields = useMemo(
    () =>
      systemFields.filter((f) => !f.autoGenerated && !f.sectionToggle && !mappedSystemKeys.has(f.key)),
    [systemFields, mappedSystemKeys],
  );
  const missingRequired = useMemo(
    () => requiredCoreFields.filter((f) => !mappedSystemKeys.has(f.key)),
    [requiredCoreFields, mappedSystemKeys],
  );
  const draftPromotedKeys = useMemo(
    () =>
      new Set(
        drafts
          .filter((d) => canPromoteDraftField(d) && d.showInInquiryList)
          .map((d) => d.fieldKey.trim())
          .filter(Boolean),
      ),
    [drafts],
  );
  const otherTemplatePromotedCount = useMemo(() => {
    let n = 0;
    for (const k of tenantPromotedKeys) {
      if (!draftPromotedKeys.has(k)) n += 1;
    }
    return n;
  }, [tenantPromotedKeys, draftPromotedKeys]);
  const promotedSlotsLeft = ORDER_FORM_INQUIRY_LIST_PROMOTED_MAX - otherTemplatePromotedCount - draftPromotedKeys.size;
  const photosSectionOn = useMemo(
    () =>
      isOrderFormSectionToggleOn(
        {
          isDefault: selected?.isDefault ?? false,
          systemFields: drafts
            .filter((d): d is DraftField & { systemField: string } => Boolean(d.systemField))
            .map((d) => ({ systemField: d.systemField, options: d.options })),
        },
        ORDER_FORM_PHOTOS_SECTION_KEY,
      ),
    [drafts, selected?.isDefault],
  );
  const itemDraftCount = drafts.filter((d) => !isOrderFormSectionToggleKey(d.systemField)).length;

  const loadTemplates = useCallback(async () => {
    if (!token) return;
    setLoading(true);
    setError(null);
    try {
      const [items, sys, promoted] = await Promise.all([
        listOrderFormTemplates(token),
        getSystemFields(token),
        getPromotedOrderFormListFields(token),
      ]);
      setTemplates(items);
      setSystemFields(sys);
      setTenantPromotedKeys(new Set(promoted.map((p) => p.fieldKey)));
      setSelectedId((prev) => {
        const fromUrl = new URLSearchParams(window.location.search).get('id');
        if (fromUrl && items.some((t) => t.id === fromUrl)) return fromUrl;
        if (prev && items.some((t) => t.id === prev)) return prev;
        return null;
      });
    } catch (e) {
      setError(e instanceof Error ? e.message : '불러오기에 실패했습니다.');
    } finally {
      setLoading(false);
    }
  }, [token]);

  useEffect(() => {
    void loadTemplates();
  }, [loadTemplates]);

  const goList = useCallback(() => {
    setSearchParams({});
    setSelectedId(null);
  }, [setSearchParams]);

  const goCreate = useCallback(
    (step = 1, draftId?: string | null) => {
      const next: Record<string, string> = { new: '1', step: String(step) };
      if (draftId) next.id = draftId;
      setSearchParams(next);
    },
    [setSearchParams],
  );

  const goEdit = useCallback(
    (id: string) => {
      setSearchParams({ id });
      setSelectedId(id);
    },
    [setSearchParams],
  );

  useEffect(() => {
    if (isCreate) return;
    if (urlId) setSelectedId(urlId);
    else setSelectedId(null);
  }, [isCreate, urlId]);

  // 선택 변경 시 편집 상태 로드
  useEffect(() => {
    if (!selected) {
      setMeta({ title: '', icon: '', description: '' });
      setDrafts([]);
      setDirty(false);
      return;
    }
    setMeta({ title: selected.title, icon: selected.icon ?? '', description: selected.description ?? '' });
    setDrafts(selected.fields.map(fieldToDraft));
    setDirty(false);
  }, [selected]);

  // 손님 화면 iframe 미리보기(기본·커스텀 공통, previewWalk)
  useEffect(() => {
    if (!token || designerPreviewToken) return;
    let cancelled = false;
    getDesignerPreviewOrderToken(token)
      .then((r) => {
        if (!cancelled) setDesignerPreviewToken(r.token);
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, [token, designerPreviewToken]);

  const designerPreviewWalkSrc = useMemo(() => {
    if (typeof window === 'undefined' || !designerPreviewToken || !selected) return '';
    return withOrderFormPreviewWalkQuery(
      appendPublicQuery(`${window.location.origin}/order/${encodeURIComponent(designerPreviewToken)}`, {
        tenantSlug: staffTenantSlug || null,
      }),
      { previewTemplateId: selected.isDefault ? null : selected.id },
    );
  }, [designerPreviewToken, selected, staffTenantSlug]);

  const flashNotice = useCallback((msg: string) => {
    setNotice(msg);
    setError(null);
    window.setTimeout(() => setNotice((n) => (n === msg ? null : n)), 3000);
  }, []);

  function updateDraft(idx: number, patch: Partial<DraftField>) {
    setDrafts((prev) => prev.map((d, i) => (i === idx ? { ...d, ...patch } : d)));
    setDirty(true);
  }

  function addOption(idx: number) {
    setDrafts((prev) => prev.map((d, i) => (i === idx ? { ...d, options: [...d.options, ''] } : d)));
    setDirty(true);
  }

  function updateOption(idx: number, optIdx: number, value: string) {
    setDrafts((prev) =>
      prev.map((d, i) =>
        i === idx ? { ...d, options: d.options.map((o, oi) => (oi === optIdx ? value : o)) } : d,
      ),
    );
    setDirty(true);
  }

  function removeOption(idx: number, optIdx: number) {
    setDrafts((prev) =>
      prev.map((d, i) => (i === idx ? { ...d, options: d.options.filter((_, oi) => oi !== optIdx) } : d)),
    );
    setDirty(true);
  }

  function setPhotosSectionOn(on: boolean) {
    const opts = optionsForOrderFormSectionToggle(on);
    setDrafts((prev) => {
      const i = prev.findIndex((d) => d.systemField === ORDER_FORM_PHOTOS_SECTION_KEY);
      if (i >= 0) {
        return prev.map((d, idx) => (idx === i ? { ...d, options: opts, label: '현장 사진 첨부' } : d));
      }
      return [
        ...prev,
        {
          fieldKey: ORDER_FORM_PHOTOS_SECTION_KEY,
          label: '현장 사진 첨부',
          helpText: null,
          inputType: 'TEXT',
          required: false,
          sortOrder: prev.length,
          systemField: ORDER_FORM_PHOTOS_SECTION_KEY,
          fillMode: 'CUSTOMER',
          options: opts,
          placeholder: null,
          optionStyle: null,
          optionLayout: null,
        },
      ];
    });
    setDirty(true);
  }

  function addSystemField(key: string) {
    const sf = systemFields.find((f) => f.key === key);
    if (!sf || mappedSystemKeys.has(key)) return;
    setDrafts((prev) => [...prev, coreFieldToDraft(sf, prev.length)]);
    setDirty(true);
  }

  function addField() {
    setDrafts((prev) => [
      ...prev,
      {
        fieldKey: `field_${prev.length + 1}`,
        label: '새 칸',
        helpText: null,
        inputType: 'TEXT',
        required: false,
        sortOrder: prev.length,
        systemField: null,
        fillMode: 'CUSTOMER',
        options: [],
        placeholder: null,
        optionStyle: null,
        optionLayout: null,
      },
    ]);
    setDirty(true);
  }

  function removeField(idx: number) {
    setDrafts((prev) => prev.filter((_, i) => i !== idx));
    setDirty(true);
  }

  /** 아직 연결되지 않은 공통 필수 항목을 항목 구성에 한번에 추가 */
  function addMissingRequiredFields() {
    setDrafts((prev) => {
      const mapped = new Set(prev.map((d) => d.systemField).filter(Boolean) as string[]);
      const toAdd = requiredFieldsForMode(systemFields, editMode)
        .filter((f) => !mapped.has(f.key))
        .map((f, i) => coreFieldToDraft(f, prev.length + i));
      if (toAdd.length === 0) return prev;
      return [...prev, ...toAdd];
    });
    setDirty(true);
  }

  function moveField(idx: number, dir: -1 | 1) {
    setDrafts((prev) => {
      const next = [...prev];
      let j = idx + dir;
      while (j >= 0 && j < next.length && isOrderFormSectionToggleKey(next[j].systemField)) {
        j += dir;
      }
      if (j < 0 || j >= next.length) return prev;
      [next[idx], next[j]] = [next[j], next[idx]];
      return next;
    });
    setDirty(true);
  }

  function upsertTemplate(updated: OrderFormTemplate) {
    setTemplates((prev) => {
      const i = prev.findIndex((t) => t.id === updated.id);
      if (i < 0) return [...prev, updated];
      return prev.map((t) => (t.id === updated.id ? updated : t));
    });
  }

  async function handleSave() {
    if (!token || !selected) return;
    setSaving(true);
    setError(null);
    try {
      if (meta.title.trim() !== selected.title || (meta.icon || '') !== (selected.icon ?? '') || (meta.description || '') !== (selected.description ?? '')) {
        await updateOrderFormTemplateMeta(token, selected.id, {
          title: meta.title.trim(),
          icon: meta.icon.trim() || null,
          description: meta.description.trim() || null,
        });
      }
      const updated = await saveOrderFormTemplateFields(token, selected.id, draftsToPayload(drafts));
      setTemplates((prev) => prev.map((t) => (t.id === updated.id ? updated : t)));
      const promoted = await getPromotedOrderFormListFields(token);
      setTenantPromotedKeys(new Set(promoted.map((p) => p.fieldKey)));
      setDirty(false);
      setDesignerPreviewIframeKey((k) => k + 1);
      flashNotice('저장했습니다.');
    } catch (e) {
      setError(e instanceof Error ? e.message : '저장에 실패했습니다.');
    } finally {
      setSaving(false);
    }
  }

  async function handlePublish() {
    if (!token || !selected) return;
    if (dirty) {
      setError('먼저 변경사항을 저장한 뒤 발행해 주세요.');
      return;
    }
    try {
      const updated = await publishOrderFormTemplate(token, selected.id);
      setTemplates((prev) => prev.map((t) => (t.id === updated.id ? updated : t)));
      flashNotice('사용함으로 바꿨습니다. 손님에게 보낼 수 있습니다.');
    } catch (e) {
      setError(e instanceof Error ? e.message : '발행에 실패했습니다.');
    }
  }

  async function handleUnpublish() {
    if (!token || !selected) return;
    try {
      const updated = await unpublishOrderFormTemplate(token, selected.id);
      setTemplates((prev) => prev.map((t) => (t.id === updated.id ? updated : t)));
      flashNotice('사용 안 함으로 바꿨습니다. 그 양식 칸은 전화 접수에서 빠집니다.');
    } catch (e) {
      setError(e instanceof Error ? e.message : '발행 해제에 실패했습니다.');
    }
  }

  async function handleToggleUse(template: OrderFormTemplate, nextOn: boolean) {
    if (!token || togglingId) return;
    setTogglingId(template.id);
    setError(null);
    try {
      const updated = nextOn
        ? await publishOrderFormTemplate(token, template.id)
        : await unpublishOrderFormTemplate(token, template.id);
      setTemplates((prev) => prev.map((t) => (t.id === updated.id ? updated : t)));
      flashNotice(
        nextOn
          ? '사용함으로 바꿨습니다. 손님에게 보낼 수 있습니다.'
          : '사용 안 함으로 바꿨습니다. 그 양식 칸은 전화 접수에서 빠집니다.',
      );
    } catch (e) {
      setError(e instanceof Error ? e.message : '사용 여부를 바꾸지 못했습니다.');
    } finally {
      setTogglingId(null);
    }
  }

  async function handleDuplicate() {
    if (!token || !selected) return;
    try {
      const created = await duplicateOrderFormTemplate(token, selected.id);
      setTemplates((prev) => [...prev, created]);
      goEdit(created.id);
      flashNotice('복제했습니다.');
    } catch (e) {
      setError(e instanceof Error ? e.message : '복제에 실패했습니다.');
    }
  }

  async function handleDelete(password: string) {
    if (!token || !selected) return;
    await deleteOrderFormTemplate(token, selected.id, password);
    setTemplates((prev) => prev.filter((t) => t.id !== selected.id));
    goList();
    flashNotice('삭제했습니다.');
  }

  const wizardDraft = isCreate && urlId ? templates.find((t) => t.id === urlId) ?? null : null;

  if (!token) return null;

  const headerBtn =
    'rounded-lg border border-slate-300 bg-white px-3.5 py-2 text-fluid-sm font-medium text-slate-700 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50';
  const headerPrimary =
    'rounded-lg bg-slate-900 px-3.5 py-2 text-fluid-sm font-medium text-white hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50';

  return (
    <div className="min-w-0 w-full max-w-full">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-1.5 flex-wrap">
            <PageTitleWithFavorite label="발주서 양식 관리">
              <h1 className="text-lg font-semibold text-gray-900 sm:text-xl">
                {isCreate ? '새 발주서 만들기' : urlId ? '발주서 양식' : '발주서 양식 관리'}
              </h1>
            </PageTitleWithFavorite>
              <HelpTooltip text="「사용하기」를 누른 양식만 손님에게 보내고 접수에서 고릅니다. 이미 보낸 서류는 「발주서 목록」입니다." />
          </div>
          <p className="mt-1 text-fluid-xs text-gray-500">
            {isCreate
              ? '한 화면씩 설정합니다. 중간에 목록으로 나가도 초안은 목록에 남습니다.'
              : urlId
                ? '이 양식만 고칩니다. 공통 안내 문구는 '
                : '아래에서 발주서를 켜고 끕니다. 공통 안내 문구는 '}
            {!isCreate ? (
              <>
                <Link to="/admin/inquiries/order-customer-preview" className="text-slate-700 underline hover:text-slate-900">
                  발주서설정
                </Link>
                입니다.
              </>
            ) : null}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {isCreate || urlId ? (
            <button type="button" onClick={goList} className={headerBtn}>
              목록으로
            </button>
          ) : null}
          {!isCreate ? (
            <button type="button" onClick={() => goCreate(1)} className={headerPrimary}>
              + 새 발주서
            </button>
          ) : null}
        </div>
      </div>

      {error && <div className="mb-3 rounded border border-red-200 bg-red-50 px-3 py-2 text-fluid-sm text-red-700">{error}</div>}
      {notice && <div className="mb-3 rounded border border-green-200 bg-green-50 px-3 py-2 text-fluid-sm text-green-700">{notice}</div>}

      {isCreate ? (
        <OrderFormTemplateCreateWizard
          token={token}
          staffTenantSlug={staffTenantSlug}
          systemFields={systemFields}
          step={wizardStep}
          draftId={isCreate ? urlId : null}
          draft={wizardDraft}
          onStepChange={goCreate}
          onCancel={goList}
          onDraftSaved={upsertTemplate}
          onOpenCreated={(id) => {
            goEdit(id);
            flashNotice('발행했습니다. 이제 발주서 발급 시 선택할 수 있습니다.');
          }}
          onSavedAsDraft={() => {
            goList();
            flashNotice('초안으로 저장했습니다. 목록에서 이어서 볼 수 있습니다.');
          }}
        />
      ) : !urlId ? (
        <div className="space-y-4">
          <OrderFormTemplateListPanel
            templates={templates}
            loading={loading}
            togglingId={togglingId}
            onOpen={goEdit}
            onToggleUse={handleToggleUse}
          />
        </div>
      ) : !selected && loading ? (
        <p className="rounded-xl border border-slate-200 bg-white p-8 text-center text-fluid-sm text-slate-400">불러오는 중…</p>
      ) : !selected ? (
        <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center">
          <p className="text-fluid-sm text-slate-500">이 양식을 찾을 수 없습니다.</p>
          <button type="button" onClick={goList} className={`${headerBtn} mt-3`}>
            목록으로
          </button>
        </div>
      ) : (
        <section className="min-w-0">
            <div className="grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,380px)]">
              <div className="min-w-0 space-y-4">
              {/* 메타 */}
              <div className="rounded-lg border border-gray-200 bg-white p-4 sm:p-5">
                <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <OrderFormTemplateStatusBadge status={selected.status} />
                    <span className="text-fluid-2xs text-gray-400">v{selected.version}</span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <button type="button" onClick={handleDuplicate} className="rounded-md border border-gray-300 px-3 py-1.5 text-fluid-xs font-medium text-gray-700 hover:bg-gray-50">
                      복제
                    </button>
                    {selected.status === 'PUBLISHED' ? (
                      <button type="button" onClick={handleUnpublish} className="rounded-md border border-amber-300 px-3 py-1.5 text-fluid-xs font-medium text-amber-700 hover:bg-amber-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2">
                        사용 안 함
                      </button>
                    ) : (
                      <button type="button" onClick={handlePublish} className="rounded-md bg-emerald-600 px-3 py-1.5 text-fluid-xs font-medium text-white hover:bg-emerald-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2">
                        사용함
                      </button>
                    )}
                    <button
                      type="button"
                      onClick={() => setDeleteOpen(true)}
                      disabled={selected.isDefault}
                      className="rounded-md border border-red-300 px-3 py-1.5 text-fluid-xs font-medium text-red-600 hover:bg-red-50 disabled:opacity-40"
                      title={selected.isDefault ? '기본 발주서는 삭제할 수 없습니다.' : undefined}
                    >
                      삭제
                    </button>
                  </div>
                </div>
                <div className="flex items-end gap-2">
                  <div className="shrink-0">
                    <span className="mb-1 block text-fluid-xs font-medium text-gray-600">아이콘</span>
                    <div className="relative">
                      <button
                        type="button"
                        onClick={() => setIconOpen((o) => !o)}
                        title={meta.icon ? ICON_OPTIONS.find((o) => o.value === meta.icon)?.label ?? '선택됨' : '아이콘 선택'}
                        aria-label="아이콘 선택"
                        className="flex h-10 items-center gap-1 rounded-md border border-gray-300 bg-white px-2.5 text-fluid-sm hover:bg-gray-50"
                      >
                        <span className="text-lg leading-none">{meta.icon || '🗂️'}</span>
                        <span className="text-fluid-2xs text-gray-400" aria-hidden>▾</span>
                      </button>
                      {iconOpen && (
                        <>
                          <button
                            type="button"
                            aria-label="닫기"
                            className="fixed inset-0 z-20 cursor-default"
                            onClick={() => setIconOpen(false)}
                          />
                          <div className="absolute left-0 top-full z-30 mt-1 w-[16.5rem] rounded-md border border-gray-200 bg-white p-2 shadow-lg">
                            <div className="grid grid-cols-6 gap-1">
                              <button
                                type="button"
                                title="없음"
                                aria-label="아이콘 없음"
                                onClick={() => {
                                  setMeta((m) => ({ ...m, icon: '' }));
                                  setDirty(true);
                                  setIconOpen(false);
                                }}
                                className={`flex h-9 items-center justify-center rounded-md border text-fluid-2xs font-medium transition ${
                                  !meta.icon ? 'border-gray-800 bg-gray-100 text-gray-800 ring-1 ring-gray-800' : 'border-gray-300 bg-white text-gray-400 hover:bg-gray-50'
                                }`}
                              >
                                없음
                              </button>
                              {ICON_OPTIONS.map((opt) => (
                                <button
                                  key={opt.value}
                                  type="button"
                                  title={opt.label}
                                  aria-label={opt.label}
                                  onClick={() => {
                                    setMeta((m) => ({ ...m, icon: opt.value }));
                                    setDirty(true);
                                    setIconOpen(false);
                                  }}
                                  className={`flex h-9 w-9 items-center justify-center rounded-md border text-lg leading-none transition ${
                                    meta.icon === opt.value
                                      ? 'border-gray-800 bg-gray-100 ring-1 ring-gray-800'
                                      : 'border-gray-300 bg-white hover:bg-gray-50'
                                  }`}
                                >
                                  {opt.value}
                                </button>
                              ))}
                            </div>
                          </div>
                        </>
                      )}
                    </div>
                  </div>
                  <label className="block min-w-0 flex-1">
                    <span className="mb-1 block text-fluid-xs font-medium text-gray-600">발주서 이름</span>
                    <input
                      value={meta.title}
                      onChange={(e) => {
                        setMeta((m) => ({ ...m, title: e.target.value }));
                        setDirty(true);
                      }}
                      maxLength={128}
                      className="w-full rounded-md border border-gray-300 px-3 py-2 text-fluid-sm"
                    />
                  </label>
                </div>
                <label className="mt-3 block">
                  <span className="mb-1 block text-fluid-xs font-medium text-gray-600">설명 (선택)</span>
                  <input
                    value={meta.description}
                    onChange={(e) => {
                      setMeta((m) => ({ ...m, description: e.target.value }));
                      setDirty(true);
                    }}
                    placeholder="내부 메모·구분용"
                    className="w-full rounded-md border border-gray-300 px-3 py-2 text-fluid-sm"
                  />
                </label>

                <p className="mt-3 border-t border-gray-100 pt-3 text-fluid-2xs leading-relaxed text-gray-500">
                  {selected.isDefault
                    ? '기본 발주서는 입주청소 양식입니다. 손님 링크와 접수 수정에는 평수·건축물·이사일 등 기존 칸이 그대로 보입니다. 항목을 지워도 손님 화면은 바뀌지 않습니다. 「현장 사진 첨부」만 아래 스위치로 끕니다. 발주서 이름은 내부 구분용입니다.'
                    : '화장실·베란다처럼 안 쓰는 칸은 항목을 지우면 손님·접수에서 사라집니다. 에어컨 대수처럼 목록에 없는 칸은 「+ 새 칸 만들기」 후 연결을 비워 두면 됩니다.'}
                </p>
              </div>

              {/* 필수 항목 체크리스트 */}
              <div className={`rounded-lg border p-4 ${missingRequired.length ? 'border-amber-200 bg-amber-50' : 'border-green-200 bg-green-50'}`}>
                <p className="text-fluid-xs font-medium text-gray-700">발행에 꼭 연결할 접수 칸</p>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {requiredCoreFields.map((f) => {
                    const ok = mappedSystemKeys.has(f.key);
                    return (
                      <span
                        key={f.key}
                        className={`rounded-full px-2 py-0.5 text-fluid-2xs font-medium ${ok ? 'bg-green-100 text-green-700' : 'bg-white text-amber-700 ring-1 ring-amber-300'}`}
                      >
                        {ok ? '✓ ' : '○ '}
                        {f.label}
                      </span>
                    );
                  })}
                </div>
                {missingRequired.length > 0 && (
                  <div className="mt-2 flex flex-wrap items-center gap-2">
                    <p className="text-fluid-2xs text-amber-700">이름·전화·주소를 항목에 넣고 접수 칸에 연결하면 발행할 수 있습니다.</p>
                    <button
                      type="button"
                      onClick={addMissingRequiredFields}
                      className="rounded-md border border-amber-400 bg-white px-2.5 py-1 text-fluid-2xs font-medium text-amber-800 hover:bg-amber-100"
                    >
                      + 이름·전화·주소 한번에 추가
                    </button>
                  </div>
                )}
              </div>

              <OrderFormSectionToggles photosOn={photosSectionOn} onPhotosChange={setPhotosSectionOn} />

              {/* 필드 빌더 */}
              <div className="rounded-lg border border-gray-200 bg-white">
                <div className="sticky top-0 z-10 flex items-center justify-between rounded-t-lg border-b border-gray-100 bg-white/95 px-4 py-3 backdrop-blur">
                  <span className="text-fluid-sm font-medium text-gray-700">항목 구성 ({itemDraftCount})</span>
                  <div className="flex flex-wrap items-center gap-1.5">
                    {unusedConnectableFields.length > 0 ? (
                      <select
                        value=""
                        onChange={(e) => {
                          const key = e.target.value;
                          if (key) addSystemField(key);
                        }}
                        className="max-w-[11rem] rounded-md border border-gray-300 bg-white px-2 py-1.5 text-fluid-xs text-gray-700 hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2"
                        aria-label="접수 칸 추가"
                      >
                        <option value="">접수 칸 추가…</option>
                        {unusedConnectableFields.map((f) => (
                          <option key={f.key} value={f.key}>
                            {f.label}
                            {f.templateRequired || f.requiredCore ? ' *' : ''}
                          </option>
                        ))}
                      </select>
                    ) : null}
                    <button
                      type="button"
                      onClick={addField}
                      className="rounded-md bg-slate-900 px-3 py-1.5 text-fluid-xs font-medium text-white hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
                    >
                      + 새 칸 만들기
                    </button>
                  </div>
                </div>
                {drafts.length === 0 ? (
                  <div className="space-y-3 p-6 text-center">
                    <p className="text-fluid-sm text-gray-400">항목이 없습니다. 이름·전화·주소부터 넣고 시작하세요.</p>
                    <button
                      type="button"
                      onClick={addMissingRequiredFields}
                      className="rounded-md bg-gray-900 px-3.5 py-2 text-fluid-xs font-medium text-white hover:bg-gray-800"
                    >
                      + 이름·전화·주소 채우기
                    </button>
                  </div>
                ) : (
                  <ul className="divide-y divide-gray-100">
                    {drafts.map((d, idx) =>
                      isOrderFormSectionToggleKey(d.systemField) ? null : (
                      <li key={d.id ?? `new-${idx}`} className="p-4">
                        <div className="mb-2 flex items-center justify-between gap-2">
                          <span className="text-fluid-2xs text-gray-400">#{idx + 1}</span>
                          <div className="flex items-center gap-1">
                            <button type="button" onClick={() => moveField(idx, -1)} disabled={!drafts.slice(0, idx).some((x) => !isOrderFormSectionToggleKey(x.systemField))} className="rounded border border-gray-200 px-2 py-0.5 text-fluid-2xs text-gray-500 hover:bg-gray-50 disabled:opacity-30">
                              ↑
                            </button>
                            <button type="button" onClick={() => moveField(idx, 1)} disabled={!drafts.slice(idx + 1).some((x) => !isOrderFormSectionToggleKey(x.systemField))} className="rounded border border-gray-200 px-2 py-0.5 text-fluid-2xs text-gray-500 hover:bg-gray-50 disabled:opacity-30">
                              ↓
                            </button>
                            <button type="button" onClick={() => removeField(idx)} className="rounded border border-red-200 px-2 py-0.5 text-fluid-2xs text-red-500 hover:bg-red-50">
                              삭제
                            </button>
                          </div>
                        </div>
                        <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
                          <label className="block">
                            <span className="mb-1 block text-fluid-2xs font-medium text-gray-500">항목 이름</span>
                            <input value={d.label} onChange={(e) => updateDraft(idx, { label: e.target.value })} maxLength={128} className="w-full rounded-md border border-gray-300 px-2.5 py-1.5 text-fluid-sm" />
                          </label>
                          <label className="block">
                            <span className="mb-1 block text-fluid-2xs font-medium text-gray-500">입력 형식</span>
                            <select value={d.inputType} onChange={(e) => updateDraft(idx, { inputType: e.target.value as OrderFormFieldInputType })} className="w-full rounded-md border border-gray-300 px-2.5 py-1.5 text-fluid-sm">
                              {INPUT_TYPE_OPTIONS.map((o) => (
                                <option key={o.value} value={o.value}>
                                  {o.label}
                                </option>
                              ))}
                            </select>
                          </label>
                          <label className="block">
                            <span className="mb-1 block text-fluid-2xs font-medium text-gray-500">
                              이미 있는 칸에 연결 (없으면 비움)
                            </span>
                            <select
                              value={d.systemField ?? ''}
                              onChange={(e) => {
                                const systemField = e.target.value || null;
                                updateDraft(idx, {
                                  systemField,
                                  ...(systemField ? { showInInquiryList: false } : {}),
                                });
                              }}
                              className="w-full rounded-md border border-gray-300 px-2.5 py-1.5 text-fluid-sm"
                            >
                              <option value="">연결 안 함 — 이 양식에만 생기는 새 칸</option>
                              {systemFields.filter((sf) => !sf.sectionToggle).map((sf) => {
                                const usedElsewhere = sf.key !== d.systemField && mappedSystemKeys.has(sf.key);
                                return (
                                  <option key={sf.key} value={sf.key} disabled={usedElsewhere || sf.autoGenerated}>
                                    {sf.label}
                                    {sf.templateRequired || sf.requiredCore ? ' *' : ''}
                                    {sf.autoGenerated ? ' (자동)' : ''}
                                    {usedElsewhere ? ' (사용중)' : ''}
                                  </option>
                                );
                              })}
                            </select>
                          </label>
                          <label className="block">
                            <span className="mb-1 block text-fluid-2xs font-medium text-gray-500">입력 주체</span>
                            <select value={d.fillMode} onChange={(e) => updateDraft(idx, { fillMode: e.target.value as OrderFormFieldFillMode })} className="w-full rounded-md border border-gray-300 px-2.5 py-1.5 text-fluid-sm">
                              {FILL_MODE_OPTIONS.map((o) => (
                                <option key={o.value} value={o.value}>
                                  {o.label}
                                </option>
                              ))}
                            </select>
                          </label>
                          {canPromoteDraftField(d) ? (
                            <label className="block sm:col-span-2">
                              <span className="mb-1 flex items-center gap-1 text-fluid-2xs font-medium text-gray-500">
                                접수 목록 표시
                                <HelpTooltip
                                  text={`서비스접수 목록에 이 추가 항목 답변을 열로 표시합니다. 업체 전체에서 동일 fieldKey 기준 최대 ${ORDER_FORM_INQUIRY_LIST_PROMOTED_MAX}개까지 선택할 수 있습니다.`}
                                />
                              </span>
                              <label className="inline-flex items-center gap-2">
                                <input
                                  type="checkbox"
                                  checked={Boolean(d.showInInquiryList)}
                                  disabled={!d.showInInquiryList && promotedSlotsLeft <= 0}
                                  onChange={(e) => updateDraft(idx, { showInInquiryList: e.target.checked })}
                                  className="h-4 w-4 rounded border-gray-300"
                                />
                                <span className="text-fluid-xs text-gray-600">
                                  목록에 노출
                                  {!d.showInInquiryList && promotedSlotsLeft <= 0
                                    ? ` (선택 한도 ${ORDER_FORM_INQUIRY_LIST_PROMOTED_MAX}개)`
                                    : ''}
                                </span>
                              </label>
                            </label>
                          ) : null}
                          <label className="block sm:col-span-2">
                            <span className="mb-1 block text-fluid-2xs font-medium text-gray-500">도움말 (선택)</span>
                            <input value={d.helpText ?? ''} onChange={(e) => updateDraft(idx, { helpText: e.target.value || null })} className="w-full rounded-md border border-gray-300 px-2.5 py-1.5 text-fluid-sm" />
                          </label>
                          {d.inputType === 'TEXTAREA' && (
                            <div className="sm:col-span-2 rounded-md border border-gray-200 bg-gray-50/60 p-2.5">
                              <label className="flex items-center gap-2">
                                <input
                                  type="checkbox"
                                  checked={d.placeholder != null}
                                  onChange={(e) => updateDraft(idx, { placeholder: e.target.checked ? '' : null })}
                                  className="h-4 w-4 rounded border-gray-300"
                                />
                                <span className="text-fluid-xs text-gray-600">입력란 안에 부연설명(흐린 안내문) 표시</span>
                              </label>
                              {d.placeholder != null && (
                                <input
                                  value={d.placeholder}
                                  onChange={(e) => updateDraft(idx, { placeholder: e.target.value })}
                                  maxLength={300}
                                  placeholder="예: 전화 상담 시 언급 내용, 층수로 나눠진 건물은 정확히 적어주세요"
                                  className="mt-2 w-full rounded-md border border-gray-300 px-2.5 py-1.5 text-fluid-sm"
                                />
                              )}
                            </div>
                          )}
                          {d.inputType === 'SELECT' && (
                            <div className="sm:col-span-2">
                              <span className="mb-1 block text-fluid-2xs font-medium text-gray-500">표시 방식</span>
                              <div className="inline-flex overflow-hidden rounded-md border border-gray-300">
                                {([
                                  { v: 'RADIO' as const, label: '라디오 버튼' },
                                  { v: 'DROPDOWN' as const, label: '드롭다운' },
                                ]).map((o) => {
                                  const active = (d.optionStyle ?? 'DROPDOWN') === o.v;
                                  return (
                                    <button
                                      key={o.v}
                                      type="button"
                                      onClick={() =>
                                        updateDraft(idx, {
                                          optionStyle: o.v,
                                          optionLayout: o.v === 'RADIO' ? d.optionLayout ?? 'VERTICAL' : null,
                                        })
                                      }
                                      className={`px-3 py-1.5 text-fluid-xs hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 ${active ? 'bg-gray-800 text-white hover:bg-gray-800' : 'bg-white text-gray-600'}`}
                                    >
                                      {o.label}
                                    </button>
                                  );
                                })}
                              </div>
                            </div>
                          )}
                          {(d.inputType === 'MULTISELECT' ||
                            d.inputType === 'CHECKBOX' ||
                            (d.inputType === 'SELECT' && (d.optionStyle ?? 'DROPDOWN') === 'RADIO')) && (
                            <div className="sm:col-span-2">
                              <span className="mb-1 block text-fluid-2xs font-medium text-gray-500">선택지 배치</span>
                              <div className="inline-flex overflow-hidden rounded-md border border-gray-300">
                                {(
                                  [
                                    { v: 'VERTICAL' as const, label: '세로' },
                                    { v: 'HORIZONTAL' as const, label: '가로' },
                                    { v: 'COLS_2' as const, label: '두 칸' },
                                  ] as const
                                ).map((o) => {
                                  const active = (d.optionLayout ?? 'VERTICAL') === o.v;
                                  return (
                                    <button
                                      key={o.v}
                                      type="button"
                                      onClick={() => updateDraft(idx, { optionLayout: o.v })}
                                      className={`px-3 py-1.5 text-fluid-xs hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 ${active ? 'bg-gray-800 text-white hover:bg-gray-800' : 'bg-white text-gray-600'}`}
                                    >
                                      {o.label}
                                    </button>
                                  );
                                })}
                              </div>
                            </div>
                          )}
                          {OPTION_INPUT_TYPES.has(d.inputType) && (
                            <div className="block sm:col-span-2">
                              <span className="mb-1 block text-fluid-2xs font-medium text-gray-500">선택지</span>
                              <div className="space-y-1.5">
                                {d.options.length === 0 ? (
                                  <p className="text-fluid-2xs text-gray-400">아래 버튼으로 선택지를 한 개씩 추가하세요.</p>
                                ) : (
                                  d.options.map((opt, optIdx) => (
                                    <div key={optIdx} className="flex items-center gap-2">
                                      <span className="text-fluid-2xs text-gray-400 w-5 text-right">{optIdx + 1}</span>
                                      <input
                                        value={opt}
                                        onChange={(e) => updateOption(idx, optIdx, e.target.value)}
                                        maxLength={128}
                                        placeholder={`선택지 ${optIdx + 1}`}
                                        className="min-w-0 flex-1 rounded-md border border-gray-300 px-2.5 py-1.5 text-fluid-sm"
                                      />
                                      <button
                                        type="button"
                                        onClick={() => removeOption(idx, optIdx)}
                                        className="shrink-0 rounded border border-red-200 px-2 py-1 text-fluid-2xs text-red-500 hover:bg-red-50"
                                      >
                                        삭제
                                      </button>
                                    </div>
                                  ))
                                )}
                              </div>
                              <button
                                type="button"
                                onClick={() => addOption(idx)}
                                className="mt-2 rounded-md border border-gray-300 px-2.5 py-1.5 text-fluid-xs font-medium text-gray-700 hover:bg-gray-50"
                              >
                                + 선택지 추가
                              </button>
                            </div>
                          )}
                          <label className="flex items-center gap-2 sm:col-span-2">
                            <input type="checkbox" checked={d.required} onChange={(e) => updateDraft(idx, { required: e.target.checked })} className="h-4 w-4 rounded border-gray-300" />
                            <span className="text-fluid-xs text-gray-600">필수 입력</span>
                            <span className="ml-2 text-fluid-2xs text-gray-400">{FILL_MODE_OPTIONS.find((o) => o.value === d.fillMode)?.hint}</span>
                          </label>
                        </div>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              {/* 저장 바 */}
              <div className="sticky bottom-0 flex items-center gap-2 rounded-lg border border-gray-200 bg-white/95 p-3 backdrop-blur">
                {dirty ? <span className="text-fluid-xs text-amber-600">저장하지 않은 변경사항이 있습니다.</span> : <span className="text-fluid-xs text-gray-400">최신 상태</span>}
                <button
                  type="button"
                  onClick={addField}
                  className="ml-auto rounded-md border border-gray-300 px-3 py-2 text-fluid-sm font-medium text-gray-700 hover:bg-gray-50"
                >
                  + 새 칸 만들기
                </button>
                <button type="button" onClick={handleSave} disabled={saving || !dirty} className="rounded-md bg-gray-900 px-4 py-2 text-fluid-sm font-medium text-white hover:bg-gray-800 disabled:opacity-40">
                  {saving ? '저장 중…' : '저장'}
                </button>
              </div>
              </div>

              {/* 우측: 손님 마법사 미리보기 — 필수 없이 다음 가능, 제출 차단 */}
              <div className="min-w-0 xl:sticky xl:top-4 xl:self-start">
                <div className="overflow-hidden rounded-lg border border-gray-200 bg-white">
                  <div className="flex items-center justify-between gap-2 border-b border-gray-100 bg-amber-50 px-3 py-2">
                    <span className="min-w-0 text-fluid-2xs font-medium leading-snug text-amber-950">
                      손님 화면 미리보기 · 필수 없이 넘기기
                      {dirty ? ' · 저장해야 반영됩니다' : ''}
                    </span>
                    {designerPreviewWalkSrc ? (
                      <a
                        href={designerPreviewWalkSrc}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="shrink-0 text-fluid-2xs font-medium text-blue-700 underline hover:text-blue-800"
                      >
                        새 탭
                      </a>
                    ) : null}
                  </div>
                  {designerPreviewWalkSrc ? (
                    <iframe
                      key={`${designerPreviewIframeKey}-${selected.id}`}
                      title="발주서 미리보기"
                      src={designerPreviewWalkSrc}
                      className="h-[min(78vh,900px)] w-full min-h-[420px] bg-gray-50"
                    />
                  ) : (
                    <OrderFormTemplatePreview meta={meta} fields={drafts} authToken={token} />
                  )}
                </div>
              </div>
            </div>
        </section>
      )}

      <ConfirmPasswordModal
        open={deleteOpen}
        title="발주서 삭제"
        description={<span>이 발주서 양식을 영구 삭제합니다. 이미 발급된 발주서는 유지되지만 양식 연결은 해제됩니다.</span>}
        confirmLabel="삭제"
        onClose={() => setDeleteOpen(false)}
        onConfirm={handleDelete}
      />
    </div>
  );
}

export default AdminOrderFormTemplatesPage;
