/**
 * 발주서 동적 템플릿 — 시스템 필드 카탈로그 (단일 소스).
 * systemField 가 지정된 템플릿 필드는 제출 시 Inquiry 정형 컬럼으로 투영된다(4단계).
 * 발행(Publish) 검증: requiredCore=true 이며 autoGenerated 아닌 항목은 템플릿에 반드시 매핑돼야 한다.
 */
export type OrderFormSystemFieldInputType =
  | 'TEXT'
  | 'TEXTAREA'
  | 'NUMBER'
  | 'MONEY'
  | 'DATE'
  | 'TIME'
  | 'PHONE'
  | 'ADDRESS'
  | 'SELECT';

export interface OrderFormSystemFieldDef {
  /** 매핑 키 (OrderFormTemplateField.systemField) */
  key: string;
  label: string;
  /** Inquiry 정형 컬럼(투영 대상). 참고용 — 4단계에서 사용 */
  inquiryColumn: string;
  /** 발행 시 반드시 폼에 있어야 하는 필수 코어 필드 */
  requiredCore: boolean;
  /**
   * TEMPLATE(템플릿 구동) 모드 발행 시 반드시 포함돼야 하는 항목.
   * 건축물유형·신축구축·평수 등은 서비스별 선택 항목(에어컨 등은 생략 가능).
   */
  templateRequired?: boolean;
  /** 서버가 자동 생성(발주서번호 등) — 폼 입력 필드로 강제하지 않음 */
  autoGenerated: boolean;
  /** 빌더 기본 입력 타입 */
  inputType: OrderFormSystemFieldInputType;
  /**
   * 표준 폼의 '섹션 토글'(사진·전문시공·견적옵션). Inquiry 정형 컬럼으로 투영하지 않고,
   * TEMPLATE 모드 공개 폼에서 해당 표준 섹션을 표시할지 여부로만 쓴다.
   */
  sectionToggle?: boolean;
}

export const ORDER_FORM_SYSTEM_FIELDS: OrderFormSystemFieldDef[] = [
  // ── 필수 코어
  { key: 'orderNumber', label: '발주서번호', inquiryColumn: 'inquiryNumber', requiredCore: true, autoGenerated: true, inputType: 'TEXT' },
  { key: 'customerName', label: '고객명', inquiryColumn: 'customerName', requiredCore: true, templateRequired: true, autoGenerated: false, inputType: 'TEXT' },
  { key: 'customerPhone', label: '전화번호', inquiryColumn: 'customerPhone', requiredCore: true, templateRequired: true, autoGenerated: false, inputType: 'PHONE' },
  { key: 'customerEmail', label: '이메일', inquiryColumn: 'customerEmail', requiredCore: true, templateRequired: true, autoGenerated: false, inputType: 'TEXT' },
  { key: 'address', label: '주소', inquiryColumn: 'address', requiredCore: true, templateRequired: true, autoGenerated: false, inputType: 'ADDRESS' },
  { key: 'totalAmount', label: '금액(총액)', inquiryColumn: 'serviceTotalAmount', requiredCore: true, autoGenerated: false, inputType: 'MONEY' },
  { key: 'areaPyeong', label: '평수', inquiryColumn: 'areaPyeong', requiredCore: true, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'preferredDate', label: '희망일', inquiryColumn: 'preferredDate', requiredCore: true, templateRequired: true, autoGenerated: false, inputType: 'DATE' },
  { key: 'preferredTime', label: '시간대', inquiryColumn: 'preferredTime', requiredCore: true, templateRequired: true, autoGenerated: false, inputType: 'SELECT' },
  // ── 선택 코어(있으면 투영, 없어도 발행 가능)
  // 보조 전화번호는 '전화번호' 섹션에 대표 연락처와 함께 고정 렌더되므로, 별도 항목으로 분리하지 않는다.
  { key: 'customerPhone2', label: '보조 전화번호', inquiryColumn: 'customerPhone2', requiredCore: false, autoGenerated: false, inputType: 'PHONE' },
  { key: 'propertyType', label: '건축물 유형', inquiryColumn: 'propertyType', requiredCore: false, autoGenerated: false, inputType: 'TEXT' },
  { key: 'buildingType', label: '신축/구축', inquiryColumn: 'buildingType', requiredCore: false, autoGenerated: false, inputType: 'TEXT' },
  { key: 'moveInDate', label: '이사일', inquiryColumn: 'moveInDate', requiredCore: false, autoGenerated: false, inputType: 'DATE' },
  { key: 'addressDetail', label: '상세주소', inquiryColumn: 'addressDetail', requiredCore: false, autoGenerated: false, inputType: 'TEXT' },
  { key: 'depositAmount', label: '예약금', inquiryColumn: 'serviceDepositAmount', requiredCore: false, autoGenerated: false, inputType: 'MONEY' },
  { key: 'balanceAmount', label: '잔금', inquiryColumn: 'serviceBalanceAmount', requiredCore: false, autoGenerated: false, inputType: 'MONEY' },
  { key: 'preferredTimeDetail', label: '희망 시각(상세)', inquiryColumn: 'preferredTimeDetail', requiredCore: false, autoGenerated: false, inputType: 'TEXT' },
  { key: 'roomCount', label: '방 개수', inquiryColumn: 'roomCount', requiredCore: false, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'bathroomCount', label: '화장실 개수', inquiryColumn: 'bathroomCount', requiredCore: false, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'balconyCount', label: '베란다 개수', inquiryColumn: 'balconyCount', requiredCore: false, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'kitchenCount', label: '주방 개수', inquiryColumn: 'kitchenCount', requiredCore: false, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'specialNotes', label: '특이사항', inquiryColumn: 'specialNotes', requiredCore: false, autoGenerated: false, inputType: 'TEXTAREA' },
  // ── 섹션 토글(투영 없음 — TEMPLATE 모드에서 표준 섹션 표시용)
  { key: 'professionalOptions', label: '전문 시공 옵션(섹션)', inquiryColumn: '-', requiredCore: false, autoGenerated: false, inputType: 'TEXT', sectionToggle: true },
  { key: 'photos', label: '현장 사진 첨부(섹션)', inquiryColumn: '-', requiredCore: false, autoGenerated: false, inputType: 'TEXT', sectionToggle: true },
];

export const ORDER_FORM_SYSTEM_FIELD_KEYS = new Set(ORDER_FORM_SYSTEM_FIELDS.map((f) => f.key));

/**
 * 기본 발주서(1번) 표준 항목 — 모든 테넌트 공통.
 * 기존에 쓰던 표준 발주서(고객명·주소·전화·평수·금액·희망일·시간대)를 기본 템플릿에 채운다.
 * 공개 화면은 시스템 필드를 표준 입력(카카오 주소검색·공급/전용 평수 등)으로 렌더하므로 inputType은 빌더 표시용.
 */
export interface DefaultTemplateFieldSeed {
  fieldKey: string;
  label: string;
  inputType: string;
  systemField: string;
  options: string[];
  sortOrder: number;
}

export const DEFAULT_ORDER_FORM_TEMPLATE_FIELDS: DefaultTemplateFieldSeed[] = [
  // 필수 코어(항상 표시)
  { fieldKey: 'customerName', label: '고객명', inputType: 'TEXT', systemField: 'customerName', options: [], sortOrder: 0 },
  { fieldKey: 'address', label: '주소', inputType: 'ADDRESS', systemField: 'address', options: [], sortOrder: 1 },
  { fieldKey: 'customerPhone', label: '전화번호', inputType: 'PHONE', systemField: 'customerPhone', options: [], sortOrder: 2 },
  { fieldKey: 'customerEmail', label: '이메일', inputType: 'TEXT', systemField: 'customerEmail', options: [], sortOrder: 13 },
  { fieldKey: 'areaPyeong', label: '평수', inputType: 'NUMBER', systemField: 'areaPyeong', options: [], sortOrder: 3 },
  { fieldKey: 'totalAmount', label: '금액(총액)', inputType: 'MONEY', systemField: 'totalAmount', options: [], sortOrder: 4 },
  { fieldKey: 'preferredDate', label: '희망일', inputType: 'DATE', systemField: 'preferredDate', options: [], sortOrder: 5 },
  { fieldKey: 'preferredTime', label: '시간대', inputType: 'SELECT', systemField: 'preferredTime', options: ['오전', '오후', '사이청소'], sortOrder: 6 },
  // 선택 표준 항목(빌더에서 숨김 가능 — 공개 폼 표준 섹션과 연결)
  { fieldKey: 'preferredTimeDetail', label: '구체적 시각', inputType: 'TEXT', systemField: 'preferredTimeDetail', options: [], sortOrder: 7 },
  { fieldKey: 'roomCount', label: '방 개수', inputType: 'NUMBER', systemField: 'roomCount', options: [], sortOrder: 8 },
  { fieldKey: 'balconyCount', label: '베란다 개수', inputType: 'NUMBER', systemField: 'balconyCount', options: [], sortOrder: 9 },
  { fieldKey: 'bathroomCount', label: '화장실 개수', inputType: 'NUMBER', systemField: 'bathroomCount', options: [], sortOrder: 10 },
  { fieldKey: 'kitchenCount', label: '주방 개수', inputType: 'NUMBER', systemField: 'kitchenCount', options: [], sortOrder: 11 },
  { fieldKey: 'specialNotes', label: '특이사항', inputType: 'TEXTAREA', systemField: 'specialNotes', options: [], sortOrder: 12 },
];

/** 발행 시 폼에 반드시 매핑돼야 하는 시스템 필드 키(자동 생성 제외) */
export const REQUIRED_CORE_SYSTEM_FIELD_KEYS = ORDER_FORM_SYSTEM_FIELDS.filter(
  (f) => f.requiredCore && !f.autoGenerated,
).map((f) => f.key);

/** TEMPLATE(템플릿 구동) 모드에서 폼에 반드시 포함돼야 하는 시스템 필드 키 */
export const TEMPLATE_MODE_REQUIRED_SYSTEM_FIELD_KEYS = ORDER_FORM_SYSTEM_FIELDS.filter(
  (f) => f.templateRequired && !f.autoGenerated,
).map((f) => f.key);

export function isKnownSystemField(key: string | null | undefined): boolean {
  return !!key && ORDER_FORM_SYSTEM_FIELD_KEYS.has(key);
}

/** 발행 검증 — 누락된 필수 코어 시스템 필드 라벨 목록 반환(빈 배열이면 통과) */
export function missingRequiredCoreFields(
  mappedSystemFields: Array<string | null | undefined>,
  renderMode: 'STANDARD' | 'TEMPLATE' = 'STANDARD',
): string[] {
  const mapped = new Set(mappedSystemFields.filter((k): k is string => !!k));
  const requiredKeys =
    renderMode === 'TEMPLATE'
      ? TEMPLATE_MODE_REQUIRED_SYSTEM_FIELD_KEYS
      : REQUIRED_CORE_SYSTEM_FIELD_KEYS;
  return requiredKeys
    .filter((k) => !mapped.has(k))
    .map((k) => ORDER_FORM_SYSTEM_FIELDS.find((f) => f.key === k)?.label ?? k);
}
