/**
 * 발주서 동적 템플릿 — 시스템 필드 카탈로그 (단일 소스).
 * systemField 가 지정된 템플릿 필드는 제출 시 Inquiry 정형 컬럼으로 투영된다(4단계).
 * 발행(Publish) 검증: requiredCore=true 이며 autoGenerated 아닌 항목은 템플릿에 반드시 매핑돼야 한다.
 */
export type OrderFormSystemFieldInputType =
  | 'TEXT'
  | 'TEXTAREA'
  | 'NUMBER'
  | 'MONEY'
  | 'DATE'
  | 'TIME'
  | 'PHONE'
  | 'ADDRESS'
  | 'SELECT';

export interface OrderFormSystemFieldDef {
  /** 매핑 키 (OrderFormTemplateField.systemField) */
  key: string;
  label: string;
  /** Inquiry 정형 컬럼(투영 대상). 참고용 — 4단계에서 사용 */
  inquiryColumn: string;
  /** 발행 시 반드시 폼에 있어야 하는 필수 코어 필드 */
  requiredCore: boolean;
  /** 서버가 자동 생성(발주서번호 등) — 폼 입력 필드로 강제하지 않음 */
  autoGenerated: boolean;
  /** 빌더 기본 입력 타입 */
  inputType: OrderFormSystemFieldInputType;
}

export const ORDER_FORM_SYSTEM_FIELDS: OrderFormSystemFieldDef[] = [
  // ── 필수 코어
  { key: 'orderNumber', label: '발주서번호', inquiryColumn: 'inquiryNumber', requiredCore: true, autoGenerated: true, inputType: 'TEXT' },
  { key: 'customerName', label: '고객명', inquiryColumn: 'customerName', requiredCore: true, autoGenerated: false, inputType: 'TEXT' },
  { key: 'customerPhone', label: '전화번호', inquiryColumn: 'customerPhone', requiredCore: true, autoGenerated: false, inputType: 'PHONE' },
  { key: 'address', label: '주소', inquiryColumn: 'address', requiredCore: true, autoGenerated: false, inputType: 'ADDRESS' },
  { key: 'totalAmount', label: '금액(총액)', inquiryColumn: 'serviceTotalAmount', requiredCore: true, autoGenerated: false, inputType: 'MONEY' },
  { key: 'areaPyeong', label: '평수', inquiryColumn: 'areaPyeong', requiredCore: true, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'preferredDate', label: '희망일', inquiryColumn: 'preferredDate', requiredCore: true, autoGenerated: false, inputType: 'DATE' },
  { key: 'preferredTime', label: '시간대', inquiryColumn: 'preferredTime', requiredCore: true, autoGenerated: false, inputType: 'SELECT' },
  // ── 선택 코어(있으면 투영, 없어도 발행 가능)
  { key: 'customerPhone2', label: '보조 전화번호', inquiryColumn: 'customerPhone2', requiredCore: false, autoGenerated: false, inputType: 'PHONE' },
  { key: 'addressDetail', label: '상세주소', inquiryColumn: 'addressDetail', requiredCore: false, autoGenerated: false, inputType: 'TEXT' },
  { key: 'depositAmount', label: '예약금', inquiryColumn: 'serviceDepositAmount', requiredCore: false, autoGenerated: false, inputType: 'MONEY' },
  { key: 'balanceAmount', label: '잔금', inquiryColumn: 'serviceBalanceAmount', requiredCore: false, autoGenerated: false, inputType: 'MONEY' },
  { key: 'preferredTimeDetail', label: '희망 시각(상세)', inquiryColumn: 'preferredTimeDetail', requiredCore: false, autoGenerated: false, inputType: 'TEXT' },
  { key: 'propertyType', label: '건물 유형', inquiryColumn: 'propertyType', requiredCore: false, autoGenerated: false, inputType: 'TEXT' },
  { key: 'roomCount', label: '방 개수', inquiryColumn: 'roomCount', requiredCore: false, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'bathroomCount', label: '화장실 개수', inquiryColumn: 'bathroomCount', requiredCore: false, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'balconyCount', label: '베란다 개수', inquiryColumn: 'balconyCount', requiredCore: false, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'kitchenCount', label: '주방 개수', inquiryColumn: 'kitchenCount', requiredCore: false, autoGenerated: false, inputType: 'NUMBER' },
  { key: 'moveInDate', label: '이사일', inquiryColumn: 'moveInDate', requiredCore: false, autoGenerated: false, inputType: 'DATE' },
  { key: 'specialNotes', label: '특이사항', inquiryColumn: 'specialNotes', requiredCore: false, autoGenerated: false, inputType: 'TEXTAREA' },
];

export const ORDER_FORM_SYSTEM_FIELD_KEYS = new Set(ORDER_FORM_SYSTEM_FIELDS.map((f) => f.key));

/** 발행 시 폼에 반드시 매핑돼야 하는 시스템 필드 키(자동 생성 제외) */
export const REQUIRED_CORE_SYSTEM_FIELD_KEYS = ORDER_FORM_SYSTEM_FIELDS.filter(
  (f) => f.requiredCore && !f.autoGenerated,
).map((f) => f.key);

export function isKnownSystemField(key: string | null | undefined): boolean {
  return !!key && ORDER_FORM_SYSTEM_FIELD_KEYS.has(key);
}

/** 발행 검증 — 누락된 필수 코어 시스템 필드 라벨 목록 반환(빈 배열이면 통과) */
export function missingRequiredCoreFields(
  mappedSystemFields: Array<string | null | undefined>,
): string[] {
  const mapped = new Set(mappedSystemFields.filter((k): k is string => !!k));
  return REQUIRED_CORE_SYSTEM_FIELD_KEYS.filter((k) => !mapped.has(k)).map(
    (k) => ORDER_FORM_SYSTEM_FIELDS.find((f) => f.key === k)?.label ?? k,
  );
}
