import { useCallback, useEffect, useMemo, useState } from 'react';
import { ORDER_FORM_INQUIRY_LIST_PROMOTED_MAX } from '@shared/orderFormListSnapshot';
import {
  ORDER_FORM_PHOTOS_SECTION_KEY,
  isOrderFormSectionToggleKey,
  isOrderFormSectionToggleOn,
  optionsForOrderFormSectionToggle,
} from '@shared/orderFormSectionToggles';
import { sanitizeTimeSlotOptionList } from '@shared/orderFormTimeSlotLabels';
import { ConfirmPasswordModal } from '../ConfirmPasswordModal';
import {
  deleteOrderFormTemplate,
  duplicateOrderFormTemplate,
  getPromotedOrderFormListFields,
  getSystemFields,
  listOrderFormTemplates,
  publishOrderFormTemplate,
  saveOrderFormTemplateFields,
  unpublishOrderFormTemplate,
  updateOrderFormTemplateMeta,
  type OrderFormSystemFieldDef,
  type OrderFormTemplate,
  type OrderFormTemplateRenderMode,
} from '../../../api/orderFormTemplates';
import { OrderFormSectionToggles } from './OrderFormSectionToggles';
import { OrderFormTemplateFieldDraftList } from './OrderFormTemplateFieldDraftList';
import { canDeleteOrderFormTemplate, OrderFormTemplateStatusBadge } from './orderFormTemplateStatus';
import {
  ICON_OPTIONS,
  canPromoteDraftField,
  coreFieldToDraft,
  draftsToPayload,
  fieldToDraft,
  isLockedAlwaysOnDraft,
  requiredFieldsForMode,
  type DraftField,
} from './orderFormTemplateDraft';

const BTN =
  'rounded-md border border-slate-300 bg-white px-3 py-1.5 text-fluid-xs font-medium text-slate-700 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50';
const BTN_PRIMARY =
  'rounded-md bg-slate-900 px-3 py-1.5 text-fluid-xs font-medium text-white hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50';

export function OrderFormTemplateEditorPanel(props: {
  token: string;
  templateId: string;
  mode: 'basics' | 'fields';
  onChanged?: (template: OrderFormTemplate) => void;
  onDeleted?: (id: string) => void;
}) {
  const { token, templateId, mode, onChanged, onDeleted } = props;
  const [selected, setSelected] = useState<OrderFormTemplate | null>(null);
  const [systemFields, setSystemFields] = useState<OrderFormSystemFieldDef[]>([]);
  const [tenantPromotedKeys, setTenantPromotedKeys] = useState<Set<string>>(new Set());
  const [meta, setMeta] = useState({ title: '', icon: '', description: '' });
  const [drafts, setDrafts] = useState<DraftField[]>([]);
  const [dirty, setDirty] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [iconOpen, setIconOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);

  const editMode: OrderFormTemplateRenderMode = selected?.isDefault ? 'STANDARD' : 'TEMPLATE';
  const requiredCoreFields = useMemo(
    () => requiredFieldsForMode(systemFields, editMode),
    [systemFields, editMode],
  );
  const mappedSystemKeys = useMemo(
    () => new Set(drafts.map((d) => d.systemField).filter(Boolean) as string[]),
    [drafts],
  );
  const unusedConnectableFields = useMemo(
    () => systemFields.filter((f) => !f.autoGenerated && !f.sectionToggle && !mappedSystemKeys.has(f.key)),
    [systemFields, mappedSystemKeys],
  );
  const missingRequired = useMemo(
    () => requiredCoreFields.filter((f) => !mappedSystemKeys.has(f.key)),
    [requiredCoreFields, mappedSystemKeys],
  );
  const draftPromotedKeys = useMemo(
    () =>
      new Set(
        drafts
          .filter((d) => canPromoteDraftField(d) && d.showInInquiryList)
          .map((d) => d.fieldKey.trim())
          .filter(Boolean),
      ),
    [drafts],
  );
  const otherTemplatePromotedCount = useMemo(() => {
    let n = 0;
    for (const k of tenantPromotedKeys) {
      if (!draftPromotedKeys.has(k)) n += 1;
    }
    return n;
  }, [tenantPromotedKeys, draftPromotedKeys]);
  const promotedSlotsLeft = ORDER_FORM_INQUIRY_LIST_PROMOTED_MAX - otherTemplatePromotedCount - draftPromotedKeys.size;
  const photosSectionOn = useMemo(
    () =>
      isOrderFormSectionToggleOn(
        {
          isDefault: selected?.isDefault ?? false,
          systemFields: drafts
            .filter((d): d is DraftField & { systemField: string } => Boolean(d.systemField))
            .map((d) => ({ systemField: d.systemField, options: d.options })),
        },
        ORDER_FORM_PHOTOS_SECTION_KEY,
      ),
    [drafts, selected?.isDefault],
  );
  const itemDraftCount = drafts.filter((d) => !isOrderFormSectionToggleKey(d.systemField)).length;

  const flash = useCallback((msg: string) => {
    setNotice(msg);
    setError(null);
    window.setTimeout(() => setNotice((n) => (n === msg ? null : n)), 3000);
  }, []);

  const applyTemplate = useCallback((row: OrderFormTemplate) => {
    setSelected(row);
    setMeta({ title: row.title, icon: row.icon ?? '', description: row.description ?? '' });
    setDrafts(row.fields.map(fieldToDraft));
    setDirty(false);
  }, []);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    Promise.all([listOrderFormTemplates(token), getSystemFields(token), getPromotedOrderFormListFields(token)])
      .then(([items, sys, promoted]) => {
        if (cancelled) return;
        setSystemFields(sys);
        setTenantPromotedKeys(new Set(promoted.map((p) => p.fieldKey)));
        const row = items.find((t) => t.id === templateId) ?? null;
        if (row) applyTemplate(row);
        else {
          setSelected(null);
          setError('이 발주서를 찾을 수 없습니다.');
        }
      })
      .catch((e) => {
        if (!cancelled) setError(e instanceof Error ? e.message : '불러오지 못했습니다.');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [token, templateId, applyTemplate]);

  function updateDraft(idx: number, patch: Partial<DraftField>) {
    setDrafts((prev) => prev.map((d, i) => (i === idx ? { ...d, ...patch } : d)));
    setDirty(true);
  }

  function setPhotosSectionOn(on: boolean) {
    const opts = optionsForOrderFormSectionToggle(on);
    setDrafts((prev) => {
      const i = prev.findIndex((d) => d.systemField === ORDER_FORM_PHOTOS_SECTION_KEY);
      if (i >= 0) {
        return prev.map((d, idx) => (idx === i ? { ...d, options: opts, label: '현장 사진 첨부' } : d));
      }
      return [
        ...prev,
        {
          fieldKey: ORDER_FORM_PHOTOS_SECTION_KEY,
          label: '현장 사진 첨부',
          helpText: null,
          inputType: 'TEXT',
          required: false,
          sortOrder: prev.length,
          systemField: ORDER_FORM_PHOTOS_SECTION_KEY,
          fillMode: 'CUSTOMER',
          options: opts,
          placeholder: null,
          optionStyle: null,
          optionLayout: null,
        },
      ];
    });
    setDirty(true);
  }

  function addSystemField(key: string) {
    const sf = systemFields.find((f) => f.key === key);
    if (!sf || mappedSystemKeys.has(key)) return;
    setDrafts((prev) => [...prev, coreFieldToDraft(sf, prev.length)]);
    setDirty(true);
  }

  function addField() {
    setDrafts((prev) => [
      ...prev,
      {
        fieldKey: `field_${prev.length + 1}`,
        label: '새 칸',
        helpText: null,
        inputType: 'TEXT',
        required: false,
        sortOrder: prev.length,
        systemField: null,
        fillMode: 'CUSTOMER',
        options: [],
        placeholder: null,
        optionStyle: null,
        optionLayout: null,
      },
    ]);
    setDirty(true);
  }

  function removeField(idx: number) {
    setDrafts((prev) => {
      const target = prev[idx];
      if (target && isLockedAlwaysOnDraft(target)) return prev;
      return prev.filter((_, i) => i !== idx);
    });
    setDirty(true);
  }

  function addMissingRequiredFields() {
    setDrafts((prev) => {
      const mapped = new Set(prev.map((d) => d.systemField).filter(Boolean) as string[]);
      const toAdd = requiredFieldsForMode(systemFields, editMode)
        .filter((f) => !mapped.has(f.key))
        .map((f, i) => coreFieldToDraft(f, prev.length + i));
      if (toAdd.length === 0) return prev;
      return [...prev, ...toAdd];
    });
    setDirty(true);
  }

  function moveField(idx: number, dir: -1 | 1) {
    setDrafts((prev) => {
      const next = [...prev];
      let j = idx + dir;
      while (j >= 0 && j < next.length && isOrderFormSectionToggleKey(next[j].systemField)) {
        j += dir;
      }
      if (j < 0 || j >= next.length) return prev;
      [next[idx], next[j]] = [next[j], next[idx]];
      return next;
    });
    setDirty(true);
  }

  async function handleSave() {
    if (!selected) return;
    setSaving(true);
    setError(null);
    try {
      if (
        meta.title.trim() !== selected.title ||
        (meta.icon || '') !== (selected.icon ?? '') ||
        (meta.description || '') !== (selected.description ?? '')
      ) {
        await updateOrderFormTemplateMeta(token, selected.id, {
          title: meta.title.trim(),
          icon: meta.icon.trim() || null,
          description: meta.description.trim() || null,
        });
      }
      const timeOpts = sanitizeTimeSlotOptionList(drafts.find((d) => d.systemField === 'preferredTime')?.options);
      if (timeOpts.length === 0) {
        throw new Error('시간대 하위 항목을 하나 이상 넣어 주세요.');
      }
      const updated = await saveOrderFormTemplateFields(token, selected.id, draftsToPayload(drafts));
      applyTemplate(updated);
      const promoted = await getPromotedOrderFormListFields(token);
      setTenantPromotedKeys(new Set(promoted.map((p) => p.fieldKey)));
      flash('저장했습니다.');
      onChanged?.(updated);
    } catch (e) {
      setError(e instanceof Error ? e.message : '저장에 실패했습니다.');
    } finally {
      setSaving(false);
    }
  }

  async function handlePublish() {
    if (!selected) return;
    if (dirty) {
      setError('먼저 변경사항을 저장한 뒤 사용함으로 바꿔 주세요.');
      return;
    }
    try {
      const updated = await publishOrderFormTemplate(token, selected.id);
      applyTemplate(updated);
      flash('사용함으로 바꿨습니다. 손님에게 보낼 수 있습니다.');
      onChanged?.(updated);
    } catch (e) {
      setError(e instanceof Error ? e.message : '사용함으로 바꾸지 못했습니다.');
    }
  }

  async function handleUnpublish() {
    if (!selected) return;
    try {
      const updated = await unpublishOrderFormTemplate(token, selected.id);
      applyTemplate(updated);
      flash('사용 안 함으로 바꿨습니다. 전화 접수 칸에서 빠집니다.');
      onChanged?.(updated);
    } catch (e) {
      setError(e instanceof Error ? e.message : '사용 끄기에 실패했습니다.');
    }
  }

  async function handleDuplicate() {
    if (!selected) return;
    try {
      const created = await duplicateOrderFormTemplate(token, selected.id);
      flash('복제했습니다. 위에서 새 발주서를 고르세요.');
      onChanged?.(created);
    } catch (e) {
      setError(e instanceof Error ? e.message : '복제에 실패했습니다.');
    }
  }

  async function handleDelete(password: string) {
    if (!selected) return;
    if (!canDeleteOrderFormTemplate(selected)) {
      throw new Error(
        selected.isDefault
          ? '기본 발주서는 삭제할 수 없습니다. 사용 끄기만 할 수 있습니다.'
          : '사용 중인 발주서는 먼저 사용 끄기를 한 뒤 삭제해 주세요.',
      );
    }
    await deleteOrderFormTemplate(token, selected.id, password);
    onDeleted?.(selected.id);
  }

  if (loading) {
    return <p className="py-4 text-center text-fluid-sm text-slate-400">불러오는 중…</p>;
  }
  if (!selected) {
    return <p className="py-4 text-center text-fluid-sm text-slate-500">{error ?? '발주서를 고르세요.'}</p>;
  }

  return (
    <div className="space-y-3">
      {error ? <p className="rounded border border-red-200 bg-red-50 px-2.5 py-1.5 text-fluid-xs text-red-700">{error}</p> : null}
      {notice ? (
        <p className="rounded border border-emerald-200 bg-emerald-50 px-2.5 py-1.5 text-fluid-xs text-emerald-800">{notice}</p>
      ) : null}

      {mode === 'basics' ? (
        <div className="space-y-3">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <OrderFormTemplateStatusBadge status={selected.status} />
              <span className="text-fluid-2xs text-gray-400">v{selected.version}</span>
            </div>
            <div className="flex flex-wrap gap-2">
              <button type="button" onClick={() => void handleDuplicate()} className={BTN}>
                복제
              </button>
              {selected.status === 'PUBLISHED' ? (
                <button type="button" onClick={() => void handleUnpublish()} className={BTN}>
                  사용 끄기
                </button>
              ) : (
                <button type="button" onClick={() => void handlePublish()} className="rounded-md bg-emerald-600 px-3 py-1.5 text-fluid-xs font-medium text-white hover:bg-emerald-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2">
                  사용하기
                </button>
              )}
              {canDeleteOrderFormTemplate(selected) ? (
                <button
                  type="button"
                  onClick={() => setDeleteOpen(true)}
                  className="rounded-md border border-red-300 px-3 py-1.5 text-fluid-xs font-medium text-red-600 hover:bg-red-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-300 focus-visible:ring-offset-2"
                >
                  삭제
                </button>
              ) : selected.isDefault ? (
                <span className="self-center text-fluid-2xs text-slate-400">기본은 끄기만 가능</span>
              ) : null}
            </div>
          </div>
          <div className="flex items-end gap-2">
            <div className="shrink-0">
              <span className="mb-1 block text-fluid-xs font-medium text-gray-600">아이콘</span>
              <div className="relative">
                <button
                  type="button"
                  onClick={() => setIconOpen((o) => !o)}
                  className="flex h-10 items-center gap-1 rounded-md border border-gray-300 bg-white px-2.5 text-fluid-sm hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400"
                >
                  <span className="text-lg leading-none">{meta.icon || '🗂️'}</span>
                  <span className="text-fluid-2xs text-gray-400">▾</span>
                </button>
                {iconOpen ? (
                  <>
                    <button type="button" aria-label="닫기" className="fixed inset-0 z-20 cursor-default" onClick={() => setIconOpen(false)} />
                    <div className="absolute left-0 top-full z-30 mt-1 w-[16.5rem] rounded-md border border-gray-200 bg-white p-2 shadow-lg">
                      <div className="grid grid-cols-6 gap-1">
                        <button
                          type="button"
                          onClick={() => {
                            setMeta((m) => ({ ...m, icon: '' }));
                            setDirty(true);
                            setIconOpen(false);
                          }}
                          className={`flex h-9 items-center justify-center rounded-md border text-fluid-2xs ${
                            !meta.icon ? 'border-slate-800 bg-slate-100' : 'border-gray-300 bg-white hover:bg-gray-50'
                          }`}
                        >
                          없음
                        </button>
                        {ICON_OPTIONS.map((opt) => (
                          <button
                            key={opt.value}
                            type="button"
                            title={opt.label}
                            onClick={() => {
                              setMeta((m) => ({ ...m, icon: opt.value }));
                              setDirty(true);
                              setIconOpen(false);
                            }}
                            className={`flex h-9 w-9 items-center justify-center rounded-md border text-lg ${
                              meta.icon === opt.value ? 'border-slate-800 bg-slate-100' : 'border-gray-300 bg-white hover:bg-gray-50'
                            }`}
                          >
                            {opt.value}
                          </button>
                        ))}
                      </div>
                    </div>
                  </>
                ) : null}
              </div>
            </div>
            <label className="block min-w-0 flex-1">
              <span className="mb-1 block text-fluid-xs font-medium text-gray-600">발주서 이름</span>
              <input
                value={meta.title}
                onChange={(e) => {
                  setMeta((m) => ({ ...m, title: e.target.value }));
                  setDirty(true);
                }}
                maxLength={128}
                className="w-full rounded-md border border-gray-300 px-3 py-2 text-fluid-sm"
              />
            </label>
          </div>
          <label className="block">
            <span className="mb-1 block text-fluid-xs font-medium text-gray-600">설명 (선택)</span>
            <input
              value={meta.description}
              onChange={(e) => {
                setMeta((m) => ({ ...m, description: e.target.value }));
                setDirty(true);
              }}
              placeholder="내부 메모·구분용"
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-fluid-sm"
            />
          </label>
          <p className="text-fluid-2xs leading-relaxed text-slate-500">
            {selected.isDefault
              ? '기본 발주서는 입주청소 양식입니다. 손님·접수에는 기존 칸이 그대로 보입니다. 현장 사진은 아래 「입력 칸」에서 끕니다.'
              : '안 쓰는 칸은 「입력 칸」에서 지우면 손님·접수에서 사라집니다.'}
          </p>
          <div className="flex items-center justify-end gap-2">
            {dirty ? <span className="text-fluid-2xs text-amber-600">저장하지 않은 변경</span> : null}
            <button type="button" onClick={() => void handleSave()} disabled={saving || !dirty} className={BTN_PRIMARY}>
              {saving ? '저장 중…' : '이름 저장'}
            </button>
          </div>
        </div>
      ) : (
        <div className="space-y-3">
          <div className={`rounded-lg border p-3 ${missingRequired.length ? 'border-amber-200 bg-amber-50' : 'border-emerald-200 bg-emerald-50'}`}>
            <p className="text-fluid-xs font-medium text-gray-700">발행에 꼭 연결할 접수 칸</p>
            <div className="mt-2 flex flex-wrap gap-1.5">
              {requiredCoreFields.map((f) => {
                const ok = mappedSystemKeys.has(f.key);
                return (
                  <span
                    key={f.key}
                    className={`rounded-full px-2 py-0.5 text-fluid-2xs font-medium ${ok ? 'bg-emerald-100 text-emerald-700' : 'bg-white text-amber-700 ring-1 ring-amber-300'}`}
                  >
                    {ok ? '✓ ' : '○ '}
                    {f.label}
                  </span>
                );
              })}
            </div>
            {missingRequired.length > 0 ? (
              <button
                type="button"
                onClick={addMissingRequiredFields}
                className="mt-2 rounded-md border border-amber-400 bg-white px-2.5 py-1 text-fluid-2xs font-medium text-amber-800 hover:bg-amber-100"
              >
                + 이름·전화·주소·서비스희망일 한번에 추가
              </button>
            ) : null}
          </div>

          <OrderFormSectionToggles photosOn={photosSectionOn} onPhotosChange={setPhotosSectionOn} />

          <div className="rounded-lg border border-gray-200 bg-white">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-gray-100 px-3 py-2">
              <span className="text-fluid-sm font-medium text-gray-700">항목 구성 ({itemDraftCount})</span>
              <div className="flex flex-wrap items-center gap-1.5">
                {unusedConnectableFields.length > 0 ? (
                  <select
                    value=""
                    onChange={(e) => {
                      const key = e.target.value;
                      if (key) addSystemField(key);
                    }}
                    className="max-w-[11rem] rounded-md border border-gray-300 bg-white px-2 py-1.5 text-fluid-xs"
                    aria-label="접수 칸 추가"
                  >
                    <option value="">접수 칸 추가…</option>
                    {unusedConnectableFields.map((f) => (
                      <option key={f.key} value={f.key}>
                        {f.label}
                        {f.templateRequired || f.requiredCore ? ' *' : ''}
                      </option>
                    ))}
                  </select>
                ) : null}
                <button type="button" onClick={addField} className={BTN_PRIMARY}>
                  + 새 칸 만들기
                </button>
              </div>
            </div>
            <OrderFormTemplateFieldDraftList
              drafts={drafts}
              systemFields={systemFields}
              mappedSystemKeys={mappedSystemKeys}
              promotedSlotsLeft={promotedSlotsLeft}
              onUpdate={updateDraft}
              onMove={moveField}
              onRemove={removeField}
              onAddMissingRequired={addMissingRequiredFields}
            />
          </div>

          <div className="sticky bottom-0 flex items-center gap-2 rounded-lg border border-gray-200 bg-white/95 p-2.5 backdrop-blur">
            {dirty ? (
              <span className="text-fluid-xs text-amber-600">저장하지 않은 변경사항이 있습니다.</span>
            ) : (
              <span className="text-fluid-xs text-gray-400">최신 상태</span>
            )}
            <button type="button" onClick={() => void handleSave()} disabled={saving || !dirty} className={`${BTN_PRIMARY} ml-auto`}>
              {saving ? '저장 중…' : '칸 저장'}
            </button>
          </div>
        </div>
      )}

      <ConfirmPasswordModal
        open={deleteOpen}
        title="발주서 삭제"
        description={<span>이 발주서 양식을 영구 삭제합니다. 이미 발급된 발주서는 유지되지만 양식 연결은 해제됩니다.</span>}
        confirmLabel="삭제"
        onClose={() => setDeleteOpen(false)}
        onConfirm={handleDelete}
      />
    </div>
  );
}
