import { InquiryStatus } from '@prisma/client';
import { OrderFollowupStatus } from '@prisma/client';
import {
  guideDemoFollowupId,
  guideDemoInquiryId,
  guideDemoOrderToken,
} from './constants.js';

export type GuideDemoInquiryScenario = {
  id: string;
  code: string;
  label: string;
  customerName: string;
  status: InquiryStatus;
  /** KST 오늘 기준 접수일 offset */
  createdDayOffset: number;
  /** KST 오늘 기준 예약일 offset */
  preferredDayOffset: number;
  preferredTime: string;
  address: string;
  addressDetail?: string;
  areaPyeong: number;
  propertyType: string;
  /** admin | marketer */
  registrar: 'admin' | 'marketer';
  /** 배정할 팀장 email (없으면 미분배) */
  teamLeaderEmails?: readonly string[];
  externalTransferFee?: number;
  withChangeLog?: boolean;
  /** 발주서 연동 — pending=미제출 pin, submitted=제출 완료 */
  orderForm?: 'pending' | 'submitted';
  orderToken?: string;
  serviceTotalAmount?: number;
};

export type GuideDemoFollowupScenario = {
  id: string;
  code: string;
  label: string;
  customerName: string;
  customerPhone: string;
  status: OrderFollowupStatus;
  deferCount?: number;
  goldDb?: boolean;
  preferredMoveInCleaningDate?: string;
  createdDayOffset: number;
};

const ADDR = {
  seoulGangnam: '서울특별시 강남구 테헤란로 152',
  seoulMapo: '서울특별시 마포구 월드컵북로 396',
  seoulSongpa: '서울특별시 송파구 올림픽로 300',
  gyeonggiGoyang: '경기도 고양시 덕양구 화신로 123',
  gyeonggiSuwon: '경기도 수원시 영통구 광교중앙로 120',
  gyeonggiSeongnam: '경기도 성남시 분당구 판교역로 146',
  incheon: '인천광역시 연수구 컨벤시아대로 204',
  busan: '부산광역시 해운대구 센텀중앙로 97',
} as const;

/** Phase 1 — 관리자 접수·발주서·대시보드 연동 (A1~A8) */
export function buildAdminInquiryScenarios(): GuideDemoInquiryScenario[] {
  return [
    // A1 — 미제출 pin (5)
    {
      id: guideDemoInquiryId(1),
      code: 'A1-01',
      label: '미제출·오늘 발급',
      customerName: '윤미제출',
      status: InquiryStatus.ORDER_FORM_PENDING,
      createdDayOffset: 0,
      preferredDayOffset: 7,
      preferredTime: '오전',
      address: ADDR.seoulGangnam,
      areaPyeong: 32,
      propertyType: '아파트',
      registrar: 'marketer',
      orderForm: 'pending',
      orderToken: guideDemoOrderToken(1),
      serviceTotalAmount: 580_000,
    },
    {
      id: guideDemoInquiryId(2),
      code: 'A1-02',
      label: '미제출·어제 발급',
      customerName: '장미제출',
      status: InquiryStatus.ORDER_FORM_PENDING,
      createdDayOffset: -1,
      preferredDayOffset: 5,
      preferredTime: '오후',
      address: ADDR.gyeonggiGoyang,
      areaPyeong: 28,
      propertyType: '아파트',
      registrar: 'marketer',
      orderForm: 'pending',
      orderToken: guideDemoOrderToken(2),
      serviceTotalAmount: 520_000,
    },
    {
      id: guideDemoInquiryId(3),
      code: 'A1-03',
      label: '미제출·3일 전',
      customerName: '임미제출',
      status: InquiryStatus.ORDER_FORM_PENDING,
      createdDayOffset: -3,
      preferredDayOffset: 10,
      preferredTime: '오전',
      address: ADDR.seoulMapo,
      areaPyeong: 24,
      propertyType: '오피스텔',
      registrar: 'marketer',
      orderForm: 'pending',
      orderToken: guideDemoOrderToken(3),
      serviceTotalAmount: 450_000,
    },
    {
      id: guideDemoInquiryId(4),
      code: 'A1-04',
      label: '미제출·날짜 필터 밖',
      customerName: '한미제출',
      status: InquiryStatus.ORDER_FORM_PENDING,
      createdDayOffset: -14,
      preferredDayOffset: 3,
      preferredTime: '사이청소',
      address: ADDR.incheon,
      areaPyeong: 30,
      propertyType: '아파트',
      registrar: 'admin',
      orderForm: 'pending',
      orderToken: guideDemoOrderToken(4),
      serviceTotalAmount: 600_000,
    },
    {
      id: guideDemoInquiryId(5),
      code: 'A1-05',
      label: '미제출·대형',
      customerName: '오미제출',
      status: InquiryStatus.ORDER_FORM_PENDING,
      createdDayOffset: -2,
      preferredDayOffset: 14,
      preferredTime: '오후',
      address: ADDR.busan,
      areaPyeong: 42,
      propertyType: '아파트',
      registrar: 'marketer',
      orderForm: 'pending',
      orderToken: guideDemoOrderToken(5),
      serviceTotalAmount: 780_000,
    },

    // A2 — 예약완료 + 접수일/예약일 분리 (12)
    {
      id: guideDemoInquiryId(10),
      code: 'A2-01',
      label: '접수 오늘·예약 내일',
      customerName: '김예약',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: 0,
      preferredDayOffset: 1,
      preferredTime: '오전',
      address: ADDR.seoulGangnam,
      areaPyeong: 33,
      propertyType: '아파트',
      registrar: 'admin',
      teamLeaderEmails: ['team1@skcleanteck.com'],
      serviceTotalAmount: 550_000,
    },
    {
      id: guideDemoInquiryId(11),
      code: 'A2-02',
      label: '접수 어제·예약 오늘',
      customerName: '이예약',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -1,
      preferredDayOffset: 0,
      preferredTime: '오후',
      address: ADDR.gyeonggiGoyang,
      areaPyeong: 29,
      propertyType: '아파트',
      registrar: 'admin',
      teamLeaderEmails: ['cbiseo'],
      serviceTotalAmount: 510_000,
    },
    {
      id: guideDemoInquiryId(12),
      code: 'A2-03',
      label: '접수·예약 모두 이번달',
      customerName: '박예약',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -5,
      preferredDayOffset: 3,
      preferredTime: '오전',
      address: ADDR.gyeonggiSuwon,
      areaPyeong: 35,
      propertyType: '아파트',
      registrar: 'marketer',
      teamLeaderEmails: ['team2@skcleanteck.com'],
      serviceTotalAmount: 620_000,
    },
    {
      id: guideDemoInquiryId(13),
      code: 'A2-04',
      label: '접수 이번달·예약 다음달',
      customerName: '최예약',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -2,
      preferredDayOffset: 20,
      preferredTime: '오후',
      address: ADDR.seoulSongpa,
      areaPyeong: 27,
      propertyType: '빌라(연립)',
      registrar: 'admin',
      serviceTotalAmount: 480_000,
    },
    {
      id: guideDemoInquiryId(14),
      code: 'A2-05',
      label: '경기 고양·대시보드 지역',
      customerName: '정고양',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -3,
      preferredDayOffset: 2,
      preferredTime: '오전',
      address: ADDR.gyeonggiGoyang,
      addressDetail: '데모 A2-05',
      areaPyeong: 31,
      propertyType: '아파트',
      registrar: 'admin',
      teamLeaderEmails: ['team1@skcleanteck.com'],
      serviceTotalAmount: 540_000,
    },
    {
      id: guideDemoInquiryId(15),
      code: 'A2-06',
      label: '부산·지역 분포',
      customerName: '강부산',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -4,
      preferredDayOffset: 5,
      preferredTime: '오후',
      address: ADDR.busan,
      areaPyeong: 36,
      propertyType: '아파트',
      registrar: 'marketer',
      teamLeaderEmails: ['cbiseo'],
      serviceTotalAmount: 590_000,
    },
    {
      id: guideDemoInquiryId(16),
      code: 'A2-07',
      label: '인천·예약일 기준',
      customerName: '조인천',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -6,
      preferredDayOffset: -1,
      preferredTime: '오전',
      address: ADDR.incheon,
      areaPyeong: 26,
      propertyType: '오피스텔',
      registrar: 'admin',
      serviceTotalAmount: 420_000,
    },
    {
      id: guideDemoInquiryId(17),
      code: 'A2-08',
      label: '성남·분당',
      customerName: '윤성남',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -7,
      preferredDayOffset: 4,
      preferredTime: '사이청소',
      address: ADDR.gyeonggiSeongnam,
      areaPyeong: 34,
      propertyType: '아파트',
      registrar: 'marketer',
      teamLeaderEmails: ['team3@skcleanteck.com'],
      serviceTotalAmount: 560_000,
    },
    {
      id: guideDemoInquiryId(18),
      code: 'A2-09',
      label: '수원 영통',
      customerName: '장수원',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -8,
      preferredDayOffset: 6,
      preferredTime: '오후',
      address: ADDR.gyeonggiSuwon,
      areaPyeong: 38,
      propertyType: '아파트',
      registrar: 'admin',
      serviceTotalAmount: 640_000,
    },
    {
      id: guideDemoInquiryId(19),
      code: 'A2-10',
      label: '마포·서울',
      customerName: '임마포',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -9,
      preferredDayOffset: 1,
      preferredTime: '오전',
      address: ADDR.seoulMapo,
      areaPyeong: 22,
      propertyType: '오피스텔',
      registrar: 'marketer',
      teamLeaderEmails: ['team2@skcleanteck.com'],
      serviceTotalAmount: 400_000,
    },
    {
      id: guideDemoInquiryId(20),
      code: 'A2-11',
      label: '송파·이번주',
      customerName: '한송파',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -10,
      preferredDayOffset: 0,
      preferredTime: '오후',
      address: ADDR.seoulSongpa,
      areaPyeong: 40,
      propertyType: '아파트',
      registrar: 'admin',
      serviceTotalAmount: 680_000,
    },
    {
      id: guideDemoInquiryId(21),
      code: 'A2-12',
      label: '강남·프리미엄',
      customerName: '오강남',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -11,
      preferredDayOffset: 8,
      preferredTime: '오전',
      address: ADDR.seoulGangnam,
      areaPyeong: 45,
      propertyType: '아파트',
      registrar: 'marketer',
      teamLeaderEmails: ['cbiseo', 'team1@skcleanteck.com'],
      serviceTotalAmount: 820_000,
    },

    // A3 — 마케터 집계 (8, marketer + RECEIVED + 이번달 접수일)
    {
      id: guideDemoInquiryId(30),
      code: 'A3-01',
      label: '마케터·오늘 접수',
      customerName: '홍집계',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: 0,
      preferredDayOffset: 2,
      preferredTime: '오전',
      address: ADDR.seoulGangnam,
      areaPyeong: 30,
      propertyType: '아파트',
      registrar: 'marketer',
      serviceTotalAmount: 500_000,
    },
    {
      id: guideDemoInquiryId(31),
      code: 'A3-02',
      label: '마케터·어제 접수',
      customerName: '서집계',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -1,
      preferredDayOffset: 3,
      preferredTime: '오후',
      address: ADDR.gyeonggiGoyang,
      areaPyeong: 28,
      propertyType: '아파트',
      registrar: 'marketer',
      serviceTotalAmount: 480_000,
    },
    {
      id: guideDemoInquiryId(32),
      code: 'A3-03',
      label: '마케터·이번달',
      customerName: '신집계',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -4,
      preferredDayOffset: 5,
      preferredTime: '오전',
      address: ADDR.incheon,
      areaPyeong: 32,
      propertyType: '아파트',
      registrar: 'marketer',
      teamLeaderEmails: ['team1@skcleanteck.com'],
      serviceTotalAmount: 530_000,
    },
    {
      id: guideDemoInquiryId(33),
      code: 'A3-04',
      label: '마케터·미분배',
      customerName: '유집계',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -2,
      preferredDayOffset: 4,
      preferredTime: '오후',
      address: ADDR.busan,
      areaPyeong: 26,
      propertyType: '빌라(연립)',
      registrar: 'marketer',
      serviceTotalAmount: 460_000,
    },
    {
      id: guideDemoInquiryId(34),
      code: 'A3-05',
      label: '마케터·drill-down',
      customerName: '권집계',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -3,
      preferredDayOffset: 7,
      preferredTime: '오전',
      address: ADDR.seoulMapo,
      areaPyeong: 24,
      propertyType: '오피스텔',
      registrar: 'marketer',
      serviceTotalAmount: 390_000,
    },
    {
      id: guideDemoInquiryId(35),
      code: 'A3-06',
      label: '마케터·고양',
      customerName: '황집계',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -5,
      preferredDayOffset: 2,
      preferredTime: '사이청소',
      address: ADDR.gyeonggiGoyang,
      areaPyeong: 36,
      propertyType: '아파트',
      registrar: 'marketer',
      serviceTotalAmount: 570_000,
    },
    {
      id: guideDemoInquiryId(36),
      code: 'A3-07',
      label: '마케터·수원',
      customerName: '안집계',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -6,
      preferredDayOffset: 9,
      preferredTime: '오후',
      address: ADDR.gyeonggiSuwon,
      areaPyeong: 33,
      propertyType: '아파트',
      registrar: 'marketer',
      serviceTotalAmount: 520_000,
    },
    {
      id: guideDemoInquiryId(37),
      code: 'A3-08',
      label: '마케터·오늘2',
      customerName: '송집계',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: 0,
      preferredDayOffset: 1,
      preferredTime: '오전',
      address: ADDR.seoulSongpa,
      areaPyeong: 29,
      propertyType: '아파트',
      registrar: 'marketer',
      teamLeaderEmails: ['cbiseo'],
      serviceTotalAmount: 495_000,
    },

    // A4 — 미분배 (8, RECEIVED + 배정 없음) — A2/A3 일부와 겹치도록 id 13,16,18,20 + 전용 4
    {
      id: guideDemoInquiryId(40),
      code: 'A4-01',
      label: '미분배·오늘 접수',
      customerName: '노미분배',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: 0,
      preferredDayOffset: 3,
      preferredTime: '오전',
      address: ADDR.gyeonggiGoyang,
      areaPyeong: 31,
      propertyType: '아파트',
      registrar: 'admin',
      serviceTotalAmount: 510_000,
    },
    {
      id: guideDemoInquiryId(41),
      code: 'A4-02',
      label: '미분배·이번달',
      customerName: '류미분배',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -2,
      preferredDayOffset: 5,
      preferredTime: '오후',
      address: ADDR.seoulGangnam,
      areaPyeong: 27,
      propertyType: '아파트',
      registrar: 'marketer',
      serviceTotalAmount: 470_000,
    },
    {
      id: guideDemoInquiryId(42),
      code: 'A4-03',
      label: '미분배·대시보드',
      customerName: '배미분배',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -1,
      preferredDayOffset: 2,
      preferredTime: '오전',
      address: ADDR.incheon,
      areaPyeong: 25,
      propertyType: '오피스텔',
      registrar: 'admin',
      serviceTotalAmount: 410_000,
    },
    {
      id: guideDemoInquiryId(43),
      code: 'A4-04',
      label: '미분배·스케줄',
      customerName: '표미분배',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -3,
      preferredDayOffset: 0,
      preferredTime: '오후',
      address: ADDR.busan,
      areaPyeong: 34,
      propertyType: '아파트',
      registrar: 'marketer',
      serviceTotalAmount: 550_000,
    },

    // A5 — 다중 배정 / 타업체 수수료 (4)
    {
      id: guideDemoInquiryId(50),
      code: 'A5-01',
      label: '2팀장 배정',
      customerName: '양팀장',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -2,
      preferredDayOffset: 4,
      preferredTime: '오전',
      address: ADDR.seoulGangnam,
      areaPyeong: 37,
      propertyType: '아파트',
      registrar: 'admin',
      teamLeaderEmails: ['cbiseo', 'team1@skcleanteck.com'],
      serviceTotalAmount: 650_000,
    },
    {
      id: guideDemoInquiryId(51),
      code: 'A5-02',
      label: '2팀장·team2+3',
      customerName: '구팀장',
      status: InquiryStatus.ASSIGNED,
      createdDayOffset: -1,
      preferredDayOffset: 2,
      preferredTime: '오후',
      address: ADDR.gyeonggiSeongnam,
      areaPyeong: 32,
      propertyType: '아파트',
      registrar: 'admin',
      teamLeaderEmails: ['team2@skcleanteck.com', 'team3@skcleanteck.com'],
      serviceTotalAmount: 540_000,
    },
    {
      id: guideDemoInquiryId(52),
      code: 'A5-03',
      label: '타업체 수수료',
      customerName: '타업체',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -4,
      preferredDayOffset: 6,
      preferredTime: '오전',
      address: ADDR.seoulMapo,
      areaPyeong: 30,
      propertyType: '아파트',
      registrar: 'admin',
      teamLeaderEmails: ['team1@skcleanteck.com'],
      externalTransferFee: 80_000,
      serviceTotalAmount: 520_000,
    },
    {
      id: guideDemoInquiryId(53),
      code: 'A5-04',
      label: 'cbiseo 단독',
      customerName: '최배정',
      status: InquiryStatus.ASSIGNED,
      createdDayOffset: 0,
      preferredDayOffset: 1,
      preferredTime: '오후',
      address: ADDR.gyeonggiGoyang,
      areaPyeong: 28,
      propertyType: '아파트',
      registrar: 'marketer',
      teamLeaderEmails: ['cbiseo'],
      serviceTotalAmount: 490_000,
    },

    // A6 — 변경이력 (3)
    {
      id: guideDemoInquiryId(60),
      code: 'A6-01',
      label: '변경이력·일정',
      customerName: '변경일정',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -5,
      preferredDayOffset: 3,
      preferredTime: '오전',
      address: ADDR.seoulSongpa,
      areaPyeong: 33,
      propertyType: '아파트',
      registrar: 'admin',
      teamLeaderEmails: ['team1@skcleanteck.com'],
      withChangeLog: true,
      serviceTotalAmount: 530_000,
    },
    {
      id: guideDemoInquiryId(61),
      code: 'A6-02',
      label: '변경이력·금액',
      customerName: '변경금액',
      status: InquiryStatus.ASSIGNED,
      createdDayOffset: -3,
      preferredDayOffset: 1,
      preferredTime: '오후',
      address: ADDR.gyeonggiSuwon,
      areaPyeong: 35,
      propertyType: '아파트',
      registrar: 'marketer',
      teamLeaderEmails: ['cbiseo'],
      withChangeLog: true,
      serviceTotalAmount: 600_000,
    },
    {
      id: guideDemoInquiryId(62),
      code: 'A6-03',
      label: '변경이력·복합',
      customerName: '변경복합',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -2,
      preferredDayOffset: 4,
      preferredTime: '오전',
      address: ADDR.incheon,
      areaPyeong: 29,
      propertyType: '빌라(연립)',
      registrar: 'admin',
      withChangeLog: true,
      serviceTotalAmount: 480_000,
    },

    // A8 — 발주서 제출 완료 (3, 발주서 목록용)
    {
      id: guideDemoInquiryId(70),
      code: 'A8-01',
      label: '발주서·제출완료',
      customerName: '제출완료',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -2,
      preferredDayOffset: 5,
      preferredTime: '오전',
      address: ADDR.seoulGangnam,
      areaPyeong: 34,
      propertyType: '아파트',
      registrar: 'marketer',
      orderForm: 'submitted',
      orderToken: guideDemoOrderToken(10),
      teamLeaderEmails: ['team2@skcleanteck.com'],
      serviceTotalAmount: 560_000,
    },
    {
      id: guideDemoInquiryId(71),
      code: 'A8-02',
      label: '발주서·제출·미배정',
      customerName: '제출미배',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -1,
      preferredDayOffset: 3,
      preferredTime: '오후',
      address: ADDR.gyeonggiGoyang,
      areaPyeong: 26,
      propertyType: '아파트',
      registrar: 'marketer',
      orderForm: 'submitted',
      orderToken: guideDemoOrderToken(11),
      serviceTotalAmount: 440_000,
    },
    {
      id: guideDemoInquiryId(72),
      code: 'A8-03',
      label: '발주서·제출·전문시공',
      customerName: '제출전문',
      status: InquiryStatus.RECEIVED,
      createdDayOffset: -4,
      preferredDayOffset: 7,
      preferredTime: '오전',
      address: ADDR.busan,
      areaPyeong: 38,
      propertyType: '아파트',
      registrar: 'marketer',
      orderForm: 'submitted',
      orderToken: guideDemoOrderToken(12),
      serviceTotalAmount: 620_000,
    },
  ];
}

export function buildAdminFollowupScenarios(): GuideDemoFollowupScenario[] {
  return [
    {
      id: guideDemoFollowupId(1),
      code: 'A7-01',
      label: '부재·1회',
      customerName: '부재고객',
      customerPhone: '010-8100-1001',
      status: OrderFollowupStatus.ABSENT,
      deferCount: 1,
      createdDayOffset: -1,
    },
    {
      id: guideDemoFollowupId(2),
      code: 'A7-02',
      label: '부재·3회',
      customerName: '부재반복',
      customerPhone: '010-8100-1002',
      status: OrderFollowupStatus.ABSENT,
      deferCount: 3,
      createdDayOffset: -3,
    },
    {
      id: guideDemoFollowupId(3),
      code: 'A7-03',
      label: '보류·고민',
      customerName: '보류고객',
      customerPhone: '010-8100-1003',
      status: OrderFollowupStatus.ON_HOLD,
      createdDayOffset: -2,
      preferredMoveInCleaningDate: undefined,
    },
    {
      id: guideDemoFollowupId(4),
      code: 'A7-04',
      label: '골드DB·예약금대기',
      customerName: '골드고객',
      customerPhone: '010-8100-1004',
      status: OrderFollowupStatus.DEPOSIT_PENDING,
      goldDb: true,
      createdDayOffset: 0,
    },
  ];
}
